import puppeteer from 'puppeteer-core';
const dist = '/Users/yoyopc/repos/kart-project/dist/index.html';
const b = await puppeteer.launch({ headless: 'new', executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', args: ['--no-sandbox','--use-gl=swiftshader','--enable-unsafe-swiftshader'] });
const page = await b.newPage();
page.on('pageerror', e => console.log('PAGEERROR', e.message));
const wait = ms => new Promise(r=>setTimeout(r,ms));
const evalp = (fn,...a) => page.evaluate(fn,...a);
await page.setViewport({ width:1366, height:768 });
await page.goto('file://' + dist, { waitUntil: 'load' });
await page.evaluate(()=>localStorage.setItem('promptracers.v1', JSON.stringify({garageTokenIntroSeen:true, quizBoxIntroSeen:true})));
await page.reload({ waitUntil: 'load' });
await page.waitForFunction('window.__DEBUG && window.__DEBUG.ready === true', { timeout: 60000 });
await page.evaluate(()=>window.__DEBUG.goto('race',{track:0,difficulty:1,autopilot:true}));
await wait(300);
await evalp(()=>window.__DEBUG.advance(6));
await evalp(()=>window.__DEBUG.engine.active.quiz.openQuestion());
await wait(80);
const box = await evalp(()=>{const r=document.querySelector('.quiz-root.show .quiz-opt').getBoundingClientRect(); return {x:r.x+r.width/2,y:r.y+r.height/2};});
const at = () => evalp(p=>{const e=document.elementFromPoint(p.x,p.y); return (e?e.className+'/'+e.tagName:null)+' ovs='+document.querySelectorAll('.mn-ov').length;}, box);
console.log('before pause:', await at());
await page.keyboard.press('Escape'); await wait(220);
console.log('with pause:  ', await at());
await page.mouse.click(box.x, box.y); await wait(140);
console.log('answered behind pause:', await evalp(()=>!!document.querySelector('.quiz-root.show .quiz-card.quiz-answered')));
await page.keyboard.press('Escape'); await wait(220);
console.log('after Esc:   ', await at());
await wait(600);
console.log('after +600ms:', await at());
await page.mouse.click(box.x, box.y); await wait(140);
console.log('answered after pause closed:', await evalp(()=>!!document.querySelector('.quiz-root.show .quiz-card.quiz-answered')),
  'phase', await evalp(()=>window.__DEBUG.engine.active.quiz.phase));
await b.close();
