import puppeteer from 'puppeteer-core';
const b=await puppeteer.launch({headless:'new',executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--no-sandbox','--use-gl=swiftshader','--enable-unsafe-swiftshader']});
const p=await b.newPage();
await p.goto('file:///Users/yoyopc/repos/kart-project/dist/index.html',{waitUntil:'load'});
await p.waitForFunction('window.__DEBUG && window.__DEBUG.ready === true',{timeout:60000});
await p.evaluate(()=>window.__DEBUG.goto('race',{track:0,difficulty:1,seed:3}));
await p.keyboard.down('ArrowUp');
for(let i=0;i<10;i++) await p.evaluate(()=>window.__DEBUG.advance(2));
console.log(await p.evaluate(()=>{const s=window.__DEBUG.engine.active;return{phase:s.state.phase,progress:+s.state.progress.toFixed(3),speed:+s.player.speed.toFixed(1),pos:s.state.position,modal:document.body.className,overlay:[...document.querySelectorAll('[class]')].map(e=>e.className).filter(c=>typeof c==='string'&&/intro|modal|card/.test(c)).slice(0,5)};}));
await b.close();
