// Track meshing: turns a TrackSpline into an actual racetrack you can look at.
//
// Everything here is generated by sweeping cross-sections along the spline's
// arc-length-uniform `t`, so road, edge lines, kerbs, run-off, barriers and
// fencing all agree with the physics (which uses `widthAt(t)` for the track
// limit and `widthAt(t) + 5.5` for the wall).
//
//   const track = buildTrack('oasis', engine);
//   scene.add(track.group);
//   track.checkpoints  -> ordered t values for lap validation
//   track.tokenSpots   -> world positions where the race spawns pickups
//
// Draw-call discipline: every sweep of the same material is accumulated into a
// SINGLE merged geometry (left + right sides, all corners, the whole lap), so
// the bare track is ~10 draw calls before scenery dressing.
import * as THREE from 'three';
import { getTrack, gridSlots } from './trackdef.js';
import { makeRng, makeNoise2D, fbm } from '../core/rng.js';
import {
  asphaltTexture, sandTexture, rockTexture, stoneWallTexture, curbTexture,
  metalTexture, woodTexture, stripeTexture, canvasTexture, disposeTextureCache,
} from '../gfx/textures.js';
import { applyTheme, getTheme } from '../gfx/sky.js';
import { dressTrack } from '../gfx/props.js';

const clamp01 = v => (v < 0 ? 0 : v > 1 ? 1 : v);
const smooth = t => t * t * (3 - 2 * t);
const sstep = (a, b, x) => smooth(clamp01((x - a) / (b - a || 1e-6)));
const lerp = (a, b, t) => a + (b - a) * t;

// Real-world texture scale, in metres per texture tile. Getting these wrong is
// the classic procedural-track tell: asphalt aggregate that reads as gravel the
// size of footballs, or kerb stripes three metres long.
const M = {
  asphalt: 3.0,      // 3 m of aggregate per tile
  sand: 6.0,
  kerbLen: 1.6,      // 2 stripes per tile -> 0.8 m stripes (real kerbs are ~0.5-1 m)
  wallLen: 4.0,      // 4 blocks per tile -> 1.0 m blocks
  wallHigh: 1.05,    // 3 courses per tile -> 0.35 m courses
};

// ---------------------------------------------------------------------------
// tiny mesh builder — merged geometry without pulling in an addon
// ---------------------------------------------------------------------------

class MB {
  constructor(useColor = false) {
    this.p = []; this.uv = []; this.c = []; this.i = []; this.useColor = useColor;
  }
  get count() { return this.p.length / 3; }
  vert(x, y, z, u, v, col) {
    this.p.push(x, y, z); this.uv.push(u, v);
    if (this.useColor) this.c.push(col ? col[0] : 1, col ? col[1] : 1, col ? col[2] : 1);
  }
  tri(a, b, c) { this.i.push(a, b, c); }
  quad(a, b, c, d) { this.i.push(a, b, d, b, c, d); }
  /** Append an axis-aligned box (used for gantry legs, plinths, kerb caps…). */
  box(cx, cy, cz, sx, sy, sz, uScale = 1, col = null, rotY = 0) {
    const co = Math.cos(rotY), si = Math.sin(rotY);
    const hx = sx / 2, hy = sy / 2, hz = sz / 2;
    const corners = [
      [-hx, -hy, -hz], [hx, -hy, -hz], [hx, hy, -hz], [-hx, hy, -hz],
      [-hx, -hy, hz], [hx, -hy, hz], [hx, hy, hz], [-hx, hy, hz],
    ].map(([x, y, z]) => [cx + x * co - z * si, cy + y, cz + x * si + z * co]);
    const faces = [
      [0, 1, 2, 3, sx, sy], [5, 4, 7, 6, sx, sy], [4, 0, 3, 7, sz, sy],
      [1, 5, 6, 2, sz, sy], [3, 2, 6, 7, sx, sz], [4, 5, 1, 0, sx, sz],
    ];
    for (const [a, b, c, d, fu, fv] of faces) {
      const n = this.count;
      const uvs = [[0, 0], [fu * uScale, 0], [fu * uScale, fv * uScale], [0, fv * uScale]];
      [a, b, c, d].forEach((vi, k) => this.vert(corners[vi][0], corners[vi][1], corners[vi][2], uvs[k][0], uvs[k][1], col));
      this.quad(n, n + 1, n + 2, n + 3);
    }
  }
  geometry(flat = false) {
    const g = new THREE.BufferGeometry();
    g.setAttribute('position', new THREE.Float32BufferAttribute(this.p, 3));
    g.setAttribute('uv', new THREE.Float32BufferAttribute(this.uv, 2));
    if (this.useColor) g.setAttribute('color', new THREE.Float32BufferAttribute(this.c, 3));
    g.setIndex(this.i);
    g.computeVertexNormals();
    if (flat) g.computeVertexNormals();
    g.computeBoundingSphere();
    return g;
  }
}

/**
 * Sweep a cross-section along the spline.
 *
 * @param mb          target MeshBuilder
 * @param spline      TrackSpline
 * @param ts          array of (possibly >1, monotonically increasing) lap fractions
 * @param sectionFn   (t, i, ramp, frame) -> [{l, h, u, col?}]  l = lateral (m),
 *                    h = height above the banked road plane (m), u = cross-section
 *                    texture coordinate
 * @param opts.vScale metres per texture tile along the track
 * @param opts.swapUV true -> uv = (alongTrack, u) instead of (u, alongTrack)
 * @param opts.taper  number of rings at each end over which `ramp` fades 0..1
 */
function sweep(mb, spline, ts, sectionFn, opts = {}) {
  const { vScale = 4, swapUV = false, taper = 0, closed = false } = opts;
  const n = ts.length;
  const R = new THREE.Vector3(), U = new THREE.Vector3();
  let prevBase = -1, cols = 0;
  for (let i = 0; i < n; i++) {
    const t = ts[i];
    const fr = spline.frameAt(((t % 1) + 1) % 1);
    const cb = Math.cos(fr.bank), sb = Math.sin(fr.bank);
    R.set(fr.right.x * cb + fr.up.x * sb, fr.right.y * cb + fr.up.y * sb, fr.right.z * cb + fr.up.z * sb);
    U.set(fr.up.x * cb - fr.right.x * sb, fr.up.y * cb - fr.right.y * sb, fr.up.z * cb - fr.right.z * sb);
    let ramp = 1;
    if (taper > 0 && !closed) ramp = Math.min(smooth(clamp01(i / taper)), smooth(clamp01((n - 1 - i) / taper)));
    const sec = sectionFn(t, i, ramp, fr);
    cols = sec.length;
    const arc = t * spline.length;
    const base = mb.count;
    for (const s of sec) {
      const x = fr.pos.x + R.x * s.l + U.x * s.h;
      const y = fr.pos.y + R.y * s.l + U.y * s.h;
      const z = fr.pos.z + R.z * s.l + U.z * s.h;
      const av = arc / vScale;
      if (swapUV) mb.vert(x, y, z, av, s.u, s.col);
      else mb.vert(x, y, z, s.u, av, s.col);
    }
    if (prevBase >= 0) {
      for (let c = 0; c < cols - 1; c++) {
        mb.quad(prevBase + c, prevBase + c + 1, base + c + 1, base + c);
      }
    }
    prevBase = base;
  }
}

/** Evenly spaced lap fractions, `count` of them, starting at 0. */
function lapTs(count) {
  const ts = new Array(count + 1);
  for (let i = 0; i <= count; i++) ts[i] = i / count;
  return ts;
}

/** Contiguous index ranges where predicate(i) holds, on a circular domain. */
function ranges(n, predicate, minLen = 3) {
  const flag = new Array(n);
  for (let i = 0; i < n; i++) flag[i] = predicate(i);
  // rotate so we always start at a false->true edge (handles wrap-around)
  let start = 0;
  while (start < n && flag[start]) start++;
  if (start === n) return [[0, n - 1]];
  const out = [];
  let i = 0, cur = null;
  for (let k = 0; k < n; k++) {
    i = (start + k) % n;
    if (flag[i]) { if (!cur) cur = [start + k, start + k]; else cur[1] = start + k; }
    else if (cur) { if (cur[1] - cur[0] + 1 >= minLen) out.push(cur); cur = null; }
  }
  if (cur && cur[1] - cur[0] + 1 >= minLen) out.push(cur);
  return out;
}

function stdMat(maps, extra = {}) {
  return new THREE.MeshStandardMaterial({
    map: maps.map || null, normalMap: maps.normalMap || null,
    roughnessMap: maps.roughnessMap || null, roughness: 1, metalness: 0, ...extra,
  });
}

/** All maps in a bundle wrap and tile 1:1 (our UVs are already in tile units). */
function tileable(maps) {
  for (const t of Object.values(maps)) {
    if (t?.isTexture) { t.wrapS = t.wrapT = THREE.RepeatWrapping; t.repeat.set(1, 1); }
  }
  return maps;
}

// ---------------------------------------------------------------------------
// signage — our own invented in-world Hebrew brands
// ---------------------------------------------------------------------------

export const BRANDS = [
  { he: 'טורבו־בינה', bg: 0xc4402f, fg: 0xffe9c4 },
  { he: 'מנוע פרומפט', bg: 0x1f6f78, fg: 0xfdf3dd },
  { he: 'ברק אנרגיה', bg: 0xe0a52c, fg: 0x3a2410 },
  { he: 'נחל נתונים', bg: 0x2f5f34, fg: 0xf2f6d8 },
  { he: 'אלגו־גיר', bg: 0x6b3f8c, fg: 0xf7e6ff },
  { he: 'שמן חכם', bg: 0xb4552a, fg: 0xffe6bf },
];

function hexCss(h) { return '#' + h.toString(16).padStart(6, '0'); }

// ---------------------------------------------------------------------------
// THE ANTI-MIRRORING RULE (Wave 4, item 7)
// ---------------------------------------------------------------------------
//
// Every piece of lettering in the 3D world is a textured quad. Whether its text
// reads forwards or backwards has NOTHING to do with which side of the track it
// sits on, or with FrontSide/DoubleSide — it depends on one thing only:
//
//     the direction in which the texture's U coordinate increases,
//     projected onto the viewer's screen-right.
//
// For a camera looking along `d`, screen-right is `d x up`. A viewer reading a
// quad looks along `-N` (N = the quad's own front normal), so
//
//     screen-right = (-N) x up = up x N            <-- SIGN_U_AXIS below
//
// So the invariant is: **U must increase along `up x N`, and V along +Y.**
// It holds for any normal, at any viewing angle, on any track — a board seen
// edge-on down a straight obeys exactly the same rule as one seen head-on.
//
// Sanity check against the two known cases:
//   * the start gantry is CORRECT: its board is a PlaneGeometry (U = local +X)
//     rotated to face back down the track (N = -tan), and up x (-tan) = right,
//     which is where local +X lands. Hence its Hebrew reads properly.
//   * the barrier sponsor boards were MIRRORED: they letter U along +tangent on
//     the right-hand side (and -tangent on the left), i.e. along `side*tan`,
//     while the rule demands `up x (-side*right) = -side*tan`. Exactly reversed,
//     on both sides, which is why the mirroring showed up on all three tracks.
//
// `enforceSignOrientation()` below is the single central place that guarantees
// the rule holds on the FINISHED track group, whoever built the geometry.
const SIGN_UP = new THREE.Vector3(0, 1, 0);

/** The one true U direction for a text quad whose front normal is `n`. */
export function signUAxis(n, out = new THREE.Vector3()) {
  return out.crossVectors(SIGN_UP, n).setY(0).normalize();
}

/**
 * Append an upright, correctly-lettered text quad.
 *
 * @param mb      target MB
 * @param c       {x,y,z} panel centre
 * @param n       front normal (horizontal; the side the text is read from)
 * @param w,h     panel size in metres
 * @param uv      [u0, v0, du, dv] rect in the texture
 */
function addSignFace(mb, c, n, w, h, uv) {
  const N = new THREE.Vector3(n.x, 0, n.z).normalize();
  const U = signUAxis(N);
  const [u0, v0, du, dv] = uv;
  const hw = w / 2, hh = h / 2;
  const base = mb.count;
  // bl, br, tr, tl — this winding gives face normal U x Y = N (see above), so
  // the quad is front-facing to exactly the viewer who can read it.
  const pts = [[-hw, -hh], [hw, -hh], [hw, hh], [-hw, hh]];
  const uvs = [[u0, v0], [u0 + du, v0], [u0 + du, v0 + dv], [u0, v0 + dv]];
  pts.forEach(([a, b], k) => mb.vert(
    c.x + U.x * a, c.y + b, c.z + U.z * a, uvs[k][0], uvs[k][1]));
  mb.quad(base, base + 1, base + 2, base + 3);
}

/** Two single-sided faces back to back — never one DoubleSide quad (see above). */
function addSignPanel(mb, c, n, w, h, uv, thickness = 0.06) {
  const N = new THREE.Vector3(n.x, 0, n.z).normalize();
  const f = { x: c.x + N.x * thickness / 2, y: c.y, z: c.z + N.z * thickness / 2 };
  const b = { x: c.x - N.x * thickness / 2, y: c.y, z: c.z - N.z * thickness / 2 };
  addSignFace(mb, f, N, w, h, uv);
  addSignFace(mb, b, N.clone().negate(), w, h, uv);
}

/**
 * Meshes whose geometry carries readable lettering. Anything named here is
 * swept by `enforceSignOrientation`; anything not named here is left alone
 * (flipping the UVs of the road would be a spectacular own goal).
 */
export const TEXT_MESHES = new Set(['boards', 'holo-signs', 'signage', 'gantry-board']);

/**
 * CENTRAL GUARANTEE: no lettering in the world is ever mirrored.
 *
 * Sweeps every text mesh in a finished track group and, per quad:
 *   1. if the face points away from the racing line, reverses its winding so it
 *      faces the driver (a DoubleSide banner hid this; a FrontSide one vanished);
 *   2. if U increases against `up x N`, mirrors the quad's U range in place —
 *      which flips the lettering back the right way round without touching the
 *      texture, the material, or any placement code.
 *
 * Running here rather than at each placement site is deliberate: signage is
 * emitted from three different modules, and this is the only choke point every
 * one of them passes through. Fixing it per-placement is how it came back.
 *
 * @returns {{repairedUV:number, repairedWinding:number, meshes:string[], bad:string[]}}
 */
export function enforceSignOrientation(group, spline, opts = {}) {
  const stat = { repairedUV: 0, repairedWinding: 0, meshes: [], bad: [] };
  const p0 = new THREE.Vector3(), p1 = new THREE.Vector3(), p2 = new THREE.Vector3();
  const e1 = new THREE.Vector3(), e2 = new THREE.Vector3();
  const N = new THREE.Vector3(), T = new THREE.Vector3(), want = new THREE.Vector3();
  const cen = new THREE.Vector3();
  group.updateMatrixWorld(true);
  // One sweep per GEOMETRY, not per mesh. The finish gantry hangs the same
  // PlaneGeometry off two meshes (one board per direction), and rewriting a
  // shared uv buffer once per mesh mangles it: the second pass takes the first
  // pass's output as its "original" and half-flips it. The invariant is
  // invariant under the rotation about Y that distinguishes the two boards
  // (U = R(+X), N = R(+Z), and up x R(+Z) = R(+X) for every angle), so one
  // sweep is not merely cheaper, it is the only coherent answer.
  const swept = new Set();

  group.traverse(o => {
    if (!o.isMesh || !TEXT_MESHES.has(o.name)) return;
    stat.meshes.push(o.name);
    // A mirrored transform or a mirrored texture repeat cannot be repaired by
    // rewriting UVs — it would just move the problem. Refuse loudly instead.
    if (o.matrixWorld.determinant() < 0) stat.bad.push(`${o.name}: negative world scale`);
    for (const m of (Array.isArray(o.material) ? o.material : [o.material])) {
      for (const key of ['map', 'emissiveMap']) {
        const tex = m?.[key];
        if (tex?.isTexture && (tex.repeat.x < 0 || tex.repeat.y < 0)) {
          stat.bad.push(`${o.name}: ${key}.repeat has a negative axis`);
        }
      }
    }
    const geo = o.geometry;
    const pos = geo?.attributes?.position, uvA = geo?.attributes?.uv, idx = geo?.index;
    if (!pos || !uvA || !idx) return;
    if (swept.has(geo.uuid)) return;
    swept.add(geo.uuid);
    const uv = uvA.array;
    const uv0 = Float32Array.from(uv);            // decisions read the ORIGINAL uvs
    const flip = new Map();                       // vertex -> [uLo, uHi]
    const tris = idx.count / 3;

    // Phase 1 — collect the upright, lettered faces of this mesh.
    //
    // `c` is the centre of the face's QUAD, not of its triangle. Every lettered
    // surface here is two triangles over four vertices (MB.quad and
    // PlaneGeometry both), and a triangle centroid sits at a CORNER of the
    // board. On a 35 m finish gantry that corner is ~17 m off the centreline, so
    // the "which side of the track am I on?" question below was being answered
    // about a corner rather than about the board — which is how a board straddling
    // the centreline got treated as a right-hand board and re-wound.
    const faces = [];
    const qc = new THREE.Vector3();
    for (let f = 0; f < tris; f++) {
      const ia = idx.getX(f * 3), ib = idx.getX(f * 3 + 1), ic = idx.getX(f * 3 + 2);
      p0.fromBufferAttribute(pos, ia).applyMatrix4(o.matrixWorld);
      p1.fromBufferAttribute(pos, ib).applyMatrix4(o.matrixWorld);
      p2.fromBufferAttribute(pos, ic).applyMatrix4(o.matrixWorld);
      e1.subVectors(p1, p0); e2.subVectors(p2, p0);
      N.crossVectors(e1, e2);
      if (N.lengthSq() < 1e-12) continue;
      N.normalize();
      if (Math.abs(N.y) > 0.8) continue;          // a lid or a floor, not lettering
      cen.copy(p0).add(p1).add(p2).multiplyScalar(1 / 3);
      // The quad: this triangle plus its partner, over their 4 distinct vertices.
      const g = (f & ~1) * 3;                     // first index of the quad's pair
      const set = new Set();
      for (let k = 0; k < 6 && g + k < idx.count; k++) set.add(idx.getX(g + k));
      if (set.size === 4) {
        qc.set(0, 0, 0);
        for (const vi of set) qc.add(p0.fromBufferAttribute(pos, vi).applyMatrix4(o.matrixWorld));
        qc.multiplyScalar(0.25);
      } else {
        qc.copy(cen);                             // not a quad: fall back honestly
      }
      faces.push({ f, ia, ib, ic, n: N.clone(), c: qc.clone(), e1: e1.clone(), e2: e2.clone() });
    }

    // Phase 2 — which faces have a back-to-back twin? A panel built as two
    // single-sided faces (the correct way to letter something readable from
    // both directions) legitimately has one face pointing away from the track,
    // and must NOT be re-wound.
    for (const a of faces) {
      // Twin test: opposite normals, and quad centres a few centimetres apart
      // through the panel. Comparing quad centres (rather than the triangle
      // centroids this used to compare) makes the distance limit mean what it
      // says: the old 16 m limit silently failed for any board wider than ~11 m,
      // because two corners of one board are further apart than that.
      a.paired = faces.some((b) => {
        if (b === a || a.n.dot(b.n) > -0.9) return false;
        const dx = a.c.x - b.c.x, dy = a.c.y - b.c.y, dz = a.c.z - b.c.z;
        const gap = Math.abs(a.n.x * dx + a.n.y * dy + a.n.z * dz);
        return gap < 0.4 && (dx * dx + dy * dy + dz * dz) < 4;
      });
    }

    // Phase 3 — repair. Decisions read the ORIGINAL uvs, so the two triangles
    // of one quad always agree and a shared vertex is never flipped twice.
    for (const fc of faces) {
      const { ia, ib, ic } = fc;
      N.copy(fc.n);
      // Which way is "toward the driver" here? Toward the centreline. A panel
      // that straddles the centreline (the finish gantry) has no such direction,
      // so the WINDING repair is skipped for it — but the U check below is not.
      // U-vs-normal is a property of the quad alone and holds wherever it sits;
      // bailing out of the whole face here is how the gantry board stayed
      // unswept even after it was named.
      const s = spline.closestT(fc.c);
      const centred = Math.abs(s.lateral) < 0.5;   // straddles the road: no "inward"
      if (!centred) {
        const right = spline.rightAt(s.t);
        const inward = -Math.sign(s.lateral);
        want.set(right.x * inward, 0, right.z * inward).normalize();
        if (!fc.paired && N.dot(want) < 0) {      // back-to-front: re-wind it
          idx.setX(fc.f * 3 + 1, ic); idx.setX(fc.f * 3 + 2, ib);
          N.negate(); fc.n.negate();
          stat.repairedWinding++;
        }
      }
      // U gradient in world space, from the standard tangent solve. It depends
      // on the uv<->position mapping only, so re-winding above cannot skew it.
      const du1 = uv0[ib * 2] - uv0[ia * 2], dv1 = uv0[ib * 2 + 1] - uv0[ia * 2 + 1];
      const du2 = uv0[ic * 2] - uv0[ia * 2], dv2 = uv0[ic * 2 + 1] - uv0[ia * 2 + 1];
      const det = du1 * dv2 - du2 * dv1;
      if (Math.abs(det) < 1e-12) continue;
      T.set(
        (fc.e1.x * dv2 - fc.e2.x * dv1) / det,
        (fc.e1.y * dv2 - fc.e2.y * dv1) / det,
        (fc.e1.z * dv2 - fc.e2.z * dv1) / det).setY(0);
      if (T.lengthSq() < 1e-12) continue;
      T.normalize();
      signUAxis(N, want);
      if (T.dot(want) >= 0) continue;             // already reads forwards
      const us = [uv0[ia * 2], uv0[ib * 2], uv0[ic * 2]];
      const lo = Math.min(...us), hi = Math.max(...us);
      for (const vi of [ia, ib, ic]) if (!flip.has(vi)) flip.set(vi, [lo, hi]);
    }
    if (flip.size) {
      for (const [vi, [lo, hi]] of flip) uv[vi * 2] = lo + hi - uv0[vi * 2];
      uvA.needsUpdate = true;
      stat.repairedUV += flip.size / 4;           // 4 verts per quad
    }
  });

  if (stat.bad.length && typeof console !== 'undefined') {
    for (const b of stat.bad) console.error(`[signage] ${b}`);
  }
  if (opts.throwOnFail && stat.bad.length) {
    throw new Error('signage: unrepairable mirroring — ' + stat.bad.join('; '));
  }
  return stat;
}

// ---------------------------------------------------------------------------
// ROADSIDE SIGNAGE — ambient curriculum (Wave 4, item 14)
// ---------------------------------------------------------------------------
//
// Two or three Hebrew words per board, at most SIGN_MAX_CHARS characters, themed
// to the track. The length limit is not style, it is optics: cap height is
// `0.4 * boardWidth / characters` (see signLayout), so every character costs the
// whole board 7% of its legibility. The first draft averaged 16 characters on a
// 7 m board and rendered at 7 px of Hebrew from the driver's seat — correct,
// well-themed curriculum that no child could read. 16 lines per track so a
// 14-board lap never repeats. All original copy; no brands, no real companies.
export const TRACK_SIGNS = {
  // נווה הנתונים — data
  oasis: {
    skin: { bg: '#efdcb8', edge: '#c4402f', fg: '#38200f', lit: 0 },
    lines: [
      'נתונים נקיים', 'תווית לדוגמה', 'אוסף אימון', 'איכות קודמת',
      'דפוס חוזר', 'מאגר נתונים', 'מודדים ומשפרים', 'עוד דוגמאות',
      'פחות טעויות', 'שדה לכל נתון', 'מיון לפי סוג', 'טבלה מסודרת',
      'רעש מסתיר דפוס', 'דוגמה טובה', 'נתונים חסרים', 'קודם בודקים',
    ],
  },
  // עיר הנוירונים — neural networks
  circuit: {
    skin: { bg: '#0d1236', edge: '#ff5fae', fg: '#8ff6ff', lit: 1.25 },
    lines: [
      'רשת נוירונים', 'שכבה על שכבה', 'משקלים לומדים', 'נוירון מדליק',
      'קלט אל פלט', 'סיבוב אימון', 'טעות מלמדת', 'חיבורים חזקים',
      'שכבה נסתרת', 'אות עובר הלאה', 'סף הפעלה', 'מתאמנים שוב',
      'זיהוי דפוסים', 'חיזוי מהיר', 'רשת עמוקה', 'למידה בשלבים',
    ],
  },
  // פסגת הענן — cloud computing
  cloud: {
    // DARK board, light letters — the reverse of the other two. Cloud Peak is a
    // white plateau under a pale dawn sky, and the original ivory-on-ivory board
    // was invisible as a SHAPE before it was ever unreadable as text. A dark
    // panel silhouetted on the plateau edge is also the frame's only altitude
    // cue from a seated camera (GAPS: "does not read as above the clouds").
    skin: { bg: '#2c3350', edge: '#ffc247', fg: '#f7f1e6', lit: 0.5 },
    lines: [
      'מחשוב ענן', 'מרכז נתונים', 'כוח לפי דרישה', 'שרת רחוק',
      'הכול מגובה', 'העלאה והורדה', 'אלפי מחשבים', 'מתרחב לפי צורך',
      'תשובה מהירה', 'אחסון בענן', 'גיבוי אוטומטי', 'חיבור מאובטח',
      'חלוקת עומס', 'זמין מכל מקום', 'רשת עולמית', 'משאב לפי מידה',
    ],
  },
};

// --- atlas geometry, stated once so the gate can re-derive a tile from a UV ---
//
// 2 x 8 = 16 tiles, so a 14-board lap never shows the same line twice (the 2 x 4
// atlas did, six times a lap). The tiles are 4:1, and the boards are built to the
// same aspect: a wide, short board is what lets a SHORT line of Hebrew be set at
// the largest cap height per square metre of board — see signLayout.
export const SIGN_COLS = 2;
export const SIGN_ROWS = 8;
/** Tile aspect (width / height) — the board's aspect must match it. */
export const SIGN_TILE_ASPECT = SIGN_ROWS / SIGN_COLS;

/**
 * Average glyph advance of the bold Hebrew face, in em. Used so sign sizing is
 * ANALYTIC and therefore measurable headlessly: `measureText` needs a real font
 * and a real canvas, so anything that decides size inside the draw callback is
 * invisible to a gate and can silently shrink to nothing (which is exactly what
 * happened — see the legibility gate in tests/signage.test.mjs).
 */
const SIGN_ADV_EM = 0.55;
/** Cap height of the Hebrew face as a fraction of the em box. */
export const SIGN_CAP_EM = 0.70;
const SIGN_FIT_W = 0.86;      // fraction of tile width the text may occupy
const SIGN_MAX_EM = 0.52;     // font size ceiling, as a fraction of tile height
/** Longest line the boards are designed to set at full size. */
export const SIGN_MAX_CHARS = 14;

/**
 * Lay a sign line out on its tile, deterministically and without a canvas.
 * @returns {{rows:string[], fontFrac:number, capFrac:number}}
 *   fontFrac/capFrac are fractions of the TILE HEIGHT, which equals the board's
 *   world height — so `capFrac * boardHeightMetres` is the glyph cap height a
 *   driver actually sees, and that is what the legibility gate projects.
 *
 * THE ONE IDENTITY WORTH REMEMBERING. While a line is width-limited,
 *
 *     capMetres = SIGN_CAP_EM * SIGN_FIT_W * boardWidthMetres / characters
 *               ≈ 0.4 * boardWidth / characters
 *
 * — the tile aspect cancels out entirely. Legible signage is therefore bought
 * with METRES OF BOARD WIDTH PER CHARACTER and with nothing else, which is why
 * the fix for 7 px Hebrew was short copy on wide boards rather than a bigger
 * font (there was no room for a bigger font) or more boards (there was no
 * shortage of boards).
 */
export function signLayout(line, aspect = SIGN_TILE_ASPECT) {
  const n = String(line).length;
  const byWidth = (SIGN_FIT_W * aspect) / (SIGN_ADV_EM * Math.max(1, n));
  const fontFrac = Math.min(SIGN_MAX_EM, byWidth);
  return { rows: [String(line)], fontFrac, capFrac: fontFrac * SIGN_CAP_EM };
}

/** UV rect of sign `i` in the sign atlas. */
export function signUV(i) {
  const N = SIGN_COLS * SIGN_ROWS;
  const k = ((i % N) + N) % N;
  const col = k % SIGN_COLS, row = (k / SIGN_COLS) | 0;
  const du = 1 / SIGN_COLS, dv = 1 / SIGN_ROWS;
  return [col * du, 1 - (row + 1) * dv, du, dv];
}

/** Eight themed sign faces baked into one atlas — one draw call for the lap. */
export function signAtlas(theme, size = 1024) {
  const set = TRACK_SIGNS[theme] || TRACK_SIGNS.oasis;
  const K = set.skin;
  return canvasTexture('signs:' + theme, size, (ctx, S) => {
    const tw = S / SIGN_COLS, th = S / SIGN_ROWS;
    ctx.fillStyle = K.bg; ctx.fillRect(0, 0, S, S);
    set.lines.forEach((line, i) => {
      const ox = (i % SIGN_COLS) * tw, oy = ((i / SIGN_COLS) | 0) * th;
      ctx.save();
      ctx.translate(ox, oy);
      ctx.fillStyle = K.bg; ctx.fillRect(0, 0, tw, th);
      // a weave/scanline so the board is not a flat colour at close range
      for (let y = 0; y < th; y += 5) {
        ctx.fillStyle = `rgba(255,255,255,${0.018 + (y % 15) * 0.001})`;
        ctx.fillRect(0, y, tw, 2);
      }
      ctx.fillStyle = K.edge;
      ctx.fillRect(0, 0, tw, th * 0.055);
      ctx.fillRect(0, th * 0.945, tw, th * 0.055);
      ctx.direction = 'rtl'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
      // Size comes from `signLayout` — analytic, canvas-free, and therefore
      // visible to the legibility gate. `measureText` is used ONLY as a safety
      // clamp for a font wider than the model expects; it can shrink, never grow,
      // and if it ever bites the gate's projection is an over-estimate.
      const lay = signLayout(line, tw / th);
      let px = Math.max(8, Math.round(th * lay.fontFrac));
      for (let g = 0; g < 4; g++) {
        ctx.font = `bold ${px}px "Arial Hebrew", "Noto Sans Hebrew", sans-serif`;
        const wpx = Math.max(...lay.rows.map(r => ctx.measureText(r)?.width || 0));
        if (wpx <= tw * SIGN_FIT_W || px <= 8) break;
        px = Math.round(px * Math.max(0.6, (tw * SIGN_FIT_W) / wpx));
      }
      ctx.font = `bold ${px}px "Arial Hebrew", "Noto Sans Hebrew", sans-serif`;
      const nR = lay.rows.length;
      const lead = px * 1.18;
      lay.rows.forEach((row, r) => {
        const cyR = th * 0.52 + (r - (nR - 1) / 2) * lead;
        ctx.fillStyle = 'rgba(0,0,0,0.30)';
        ctx.fillText(row, tw / 2 + tw * 0.006, cyR + th * 0.014);
        ctx.fillStyle = K.fg;
        ctx.fillText(row, tw / 2, cyR);
      });
      ctx.restore();
    });
  });
}

/** A sponsor board / banner face. Cached by brand index + size. */
export function brandTexture(index, size = 256) {
  const b = BRANDS[index % BRANDS.length];
  return canvasTexture(`brand${index % BRANDS.length}`, size, (ctx, S) => {
    const H = S / 4;
    ctx.fillStyle = hexCss(b.bg);
    ctx.fillRect(0, 0, S, S);
    // faded canvas weave so the board is not a flat colour
    for (let i = 0; i < 900; i++) {
      const x = (i * 97) % S, y = (i * 181) % S;
      ctx.fillStyle = `rgba(255,255,255,${0.012 + ((i * 13) % 7) * 0.004})`;
      ctx.fillRect(x, y, 3, 2);
    }
    ctx.fillStyle = hexCss(b.fg);
    ctx.globalAlpha = 0.22;
    ctx.fillRect(0, S * 0.06, S, S * 0.02);
    ctx.fillRect(0, S * 0.92, S, S * 0.02);
    ctx.globalAlpha = 1;
    ctx.direction = 'rtl';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.font = `bold ${Math.round(S * 0.19)}px "Arial Hebrew", "Noto Sans Hebrew", sans-serif`;
    ctx.fillStyle = 'rgba(0,0,0,0.28)';
    ctx.fillText(b.he, S / 2 + S * 0.008, S / 2 + S * 0.012);
    ctx.fillStyle = hexCss(b.fg);
    ctx.fillText(b.he, S / 2, S / 2);
    void H;
  }, { wrap: THREE.RepeatWrapping });
}

/** The start gantry face: track name + a couple of brand strips. */
const GANTRY_SKIN = {
  oasis: { a: '#3a2418', b: '#5c3a22', c: '#2c1a11', rule: '#ffc247', text: '#ffd98a', lamp: ['rgba(255,246,214,0.95)', 'rgba(255,200,110,0)'] },
  circuit: { a: '#0b1030', b: '#241a4d', c: '#080b22', rule: '#39e6ff', text: '#c9f6ff', lamp: ['rgba(180,246,255,0.95)', 'rgba(255,95,174,0)'] },
  cloud: { a: '#e8dfd4', b: '#fbf3e6', c: '#d8cec2', rule: '#ffc247', text: '#7a5a2a', lamp: ['rgba(255,246,220,0.95)', 'rgba(255,214,150,0)'] },
};

function gantryTexture(nameHe, size = 512, theme = 'oasis') {
  const K = GANTRY_SKIN[theme] || GANTRY_SKIN.oasis;
  return canvasTexture('gantry:' + nameHe, size, (ctx, S) => {
    const H = S / 4;                       // the beam is 4:1
    const g = ctx.createLinearGradient(0, 0, 0, H);
    g.addColorStop(0, K.a); g.addColorStop(0.5, K.b); g.addColorStop(1, K.c);
    ctx.fillStyle = K.c; ctx.fillRect(0, 0, S, S);
    ctx.fillStyle = g; ctx.fillRect(0, 0, S, H);
    // accent rule lines
    ctx.fillStyle = K.rule;
    ctx.fillRect(0, H * 0.06, S, H * 0.035);
    ctx.fillRect(0, H * 0.90, S, H * 0.035);
    ctx.direction = 'rtl'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
    ctx.font = `bold ${Math.round(H * 0.48)}px "Arial Hebrew", "Noto Sans Hebrew", sans-serif`;
    ctx.fillStyle = 'rgba(0,0,0,0.45)';
    ctx.fillText(nameHe, S / 2, H * 0.53 + H * 0.02);
    ctx.fillStyle = K.text;
    ctx.fillText(nameHe, S / 2, H * 0.51);
    // lamp strip along the bottom
    const lamps = 26;
    for (let i = 0; i < lamps; i++) {
      const x = (i + 0.5) / lamps * S;
      const r = H * 0.045;
      const rg = ctx.createRadialGradient(x, H * 0.965, 0, x, H * 0.965, r * 2.6);
      rg.addColorStop(0, K.lamp[0]); rg.addColorStop(1, K.lamp[1]);
      ctx.fillStyle = rg; ctx.beginPath(); ctx.arc(x, H * 0.965, r * 2.6, 0, 7); ctx.fill();
    }
  });
}

/** Chequered flag pattern for the start/finish line. */
function chequerTexture(size = 128) {
  return canvasTexture('chequer', size, (ctx, S) => {
    const n = 8;
    for (let y = 0; y < n; y++) {
      for (let x = 0; x < n; x++) {
        const on = (x + y) % 2 === 0;
        ctx.fillStyle = on ? '#eceae2' : '#22211f';
        ctx.fillRect(x * S / n, y * S / n, S / n + 1, S / n + 1);
        // scuff so it is not a perfect vector checker
        ctx.fillStyle = `rgba(${on ? '90,86,78' : '210,206,196'},${0.03 + ((x * 7 + y * 3) % 5) * 0.012})`;
        ctx.fillRect(x * S / n, y * S / n, S / n, S / n);
      }
    }
  }, { wrap: THREE.RepeatWrapping });
}

// ---------------------------------------------------------------------------
// buildTrack
// ---------------------------------------------------------------------------

/**
 * Build the full track mesh set for a track id (or index).
 *
 * @returns {{group:THREE.Group, spline, def, checkpoints:number[],
 *            tokenSpots:THREE.Vector3[], heightAt:(x,z)=>number,
 *            dress:object|null, update:(t)=>void, dispose:()=>void}}
 */
export function buildTrack(idOrIndex, engine, opts = {}) {
  const { def, spline } = getTrack(idOrIndex);
  const q = engine?.q || { texSize: 1024, shadows: true, propDensity: 1, crowdDensity: 1, drawDistance: 700 };
  const theme = getTheme(def.theme);
  const S = q.texSize;
  const rng = makeRng(1000 + def.id.length * 37 + def.points.length);
  const noise = makeNoise2D(4400 + def.laps * 13);

  const group = new THREE.Group();
  group.name = 'track:' + def.id;
  const geos = [], mats = [], disposables = [];
  const keep = (m) => { mats.push(m); return m; };

  const L = spline.length;
  const detail = q.propDensity >= 0.9 ? 1 : q.propDensity >= 0.6 ? 0.72 : 0.5;
  const RINGS = Math.max(180, Math.round(L / (2.0 / detail)));   // ~2 m per ring at high
  const ts = lapTs(RINGS);

  // ---- palettes per theme (oasis is the Wave-1 flagship) -------------------
  const P = {
    oasis: {
      asphalt: 0x4a4744, sandTint: 0xd8ae6f, dustTint: 0xc79a5f,
      wall: 0xd3b083, wallMortar: 0x9a7f5c, rock: 0xa9603a,
      kerbA: 0xc23026, kerbB: 0xf0e6d6, paint: 0xe9e3d2,
    },
    circuit: {
      asphalt: 0x3b3e46, sandTint: 0x5a5f63, dustTint: 0x4a4e55,
      wall: 0x6f7480, wallMortar: 0x4a4e57, rock: 0x4a4458,
      kerbA: 0xbe2b58, kerbB: 0xe8e4ee, paint: 0xdfe6f2,
    },
    cloud: {
      // warm ivory, not lavender: at dawn the plateau catches the gold, and a
      // cool grey run-off next to a warm sky reads as a rendering mistake
      asphalt: 0x585b63, sandTint: 0xd9d1c5, dustTint: 0xcdc5b8,
      wall: 0xd7d2dd, wallMortar: 0xa39fae, rock: 0x8e8c9e,
      kerbA: 0xc44a6e, kerbB: 0xf6f2f6, paint: 0xf2eee6,
    },
  }[def.theme] || {};

  // =========================================================================
  // 1. ROAD
  // =========================================================================
  // At 256 px the aggregate is drawn at ~4x the pixel density of the 1024 map,
  // so a 3 m tile turns the low tier into cobblestones. Scale the tile with the
  // texture instead of hard-coding it.
  const asphaltTile = M.asphalt * (S >= 512 ? 1 : 1.6);
  const asph = tileable(asphaltTexture({ size: S, tint: P.asphalt, wetness: def.theme === 'circuit' ? 0.85 : 0 }));
  const roadMat = keep(stdMat(asph, {
    metalness: def.theme === 'circuit' ? 0.22 : 0.0,
    vertexColors: true,
    // The aggregate height field is authored for a 1024 map. At 256 the same
    // normals cover 4x the area each and the road turns into cobbles, so the
    // low tier keeps the albedo grain and drops most of the relief.
    normalScale: new THREE.Vector2(1, 1).multiplyScalar(S >= 512 ? 1 : 0.4),
  }));
  {
    const mb = new MB(true);
    const COLS = 8;                                   // 9 columns across
    sweep(mb, spline, ts, (t) => {
      const w = spline.widthAt(t);
      const sec = [];
      // faint tyre-polished lanes: two darker bands where the racing line runs
      for (let c = 0; c <= COLS; c++) {
        const f = c / COLS * 2 - 1;                   // -1..1
        const l = f * w;
        const lane = Math.exp(-Math.pow((Math.abs(f) - 0.42) / 0.20, 2));
        const dirt = 1 - sstep(0.72, 1.0, Math.abs(f)) * 0.16;   // grubbier at the edges
        const k = (1 - lane * 0.10) * dirt;
        sec.push({ l, h: 0, u: l / asphaltTile, col: [k, k * 0.995, k * 0.985] });
      }
      return sec;
    }, { vScale: asphaltTile, closed: true });
    const g = mb.geometry(); geos.push(g);
    const road = new THREE.Mesh(g, roadMat);
    road.receiveShadow = !!q.shadows;
    road.name = 'road';
    group.add(road);
  }

  // =========================================================================
  // 2. WHITE PAINT — edge lines, start line box, grid markings
  // =========================================================================
  const paintMat = keep(new THREE.MeshStandardMaterial({
    color: P.paint, roughness: 0.82, metalness: 0,
    polygonOffset: true, polygonOffsetFactor: -4, polygonOffsetUnits: -6,
  }));
  {
    const mb = new MB(false);
    for (const side of [-1, 1]) {
      sweep(mb, spline, ts, (t) => {
        const w = spline.widthAt(t);
        const a = side * (w - 0.42), b = side * (w - 0.10);
        return [{ l: Math.min(a, b), h: 0.015, u: 0 }, { l: Math.max(a, b), h: 0.015, u: 1 }];
      }, { vScale: 2, closed: true });
    }
    // starting grid boxes — two columns, four rows behind the line
    const slots = gridSlots(spline, def, 8);
    const BW = 1.05, BL = 2.4, TH = 0.14;
    for (const s of slots) {
      const fr = spline.frameAt(s.t);
      const dAlong = BL / L;
      // 3 sides of an open box (the front edge stays open, like the reference)
      const parts = [
        [s.lateral - BW, s.lateral - BW + TH, -dAlong, dAlong],
        [s.lateral + BW - TH, s.lateral + BW, -dAlong, dAlong],
        [s.lateral - BW, s.lateral + BW, -dAlong, -dAlong + TH / L * 6],
      ];
      for (const [l0, l1, t0, t1] of parts) {
        const n = mb.count;
        const corners = [[l0, t0], [l1, t0], [l1, t1], [l0, t1]];
        for (const [l, dt] of corners) {
          const f2 = spline.frameAt(((s.t + dt) % 1 + 1) % 1);
          mb.vert(f2.pos.x + f2.right.x * l, f2.pos.y + 0.016, f2.pos.z + f2.right.z * l, 0, 0);
        }
        mb.quad(n, n + 1, n + 2, n + 3);
      }
      void fr;
    }
    const g = mb.geometry(); geos.push(g);
    const paint = new THREE.Mesh(g, paintMat);
    paint.receiveShadow = false;
    paint.name = 'paint';
    group.add(paint);
  }

  // =========================================================================
  // 3. KERBS — corners only, on the inside of the turn
  // =========================================================================
  const kerbMaps = tileable(curbTexture({
    size: Math.min(S, 512), colorA: P.kerbA, colorB: P.kerbB, stripes: 2, wear: 0.6, axis: 'v',
  }));
  const kerbMat = keep(stdMat(kerbMaps, { roughness: 0.85 }));
  const curvOf = i => spline.curvatureAt(ts[i % RINGS]);
  {
    const mb = new MB(false);
    const KERB_T = 0.055;                    // ~R < 200 m counts as a corner
    for (const sgn of [-1, 1]) {
      // sgn is the side of the road the kerb sits on, and a kerb belongs on the
      // INSIDE of the corner.
      //
      // NOTE: trackdef's docstring says "positive curvature = turning left",
      // but the maths says otherwise — it builds `cross = a.x*b.z - a.z*b.x`,
      // which is MINUS the y component of a x b, so a positive value is a
      // clockwise (right-hand) turn. Verified on screen: with the naive reading
      // every kerb landed on the outside of its corner. Inside == sign(c).
      const rs = ranges(RINGS, i => {
        const c = curvOf(i);
        return Math.abs(c) > KERB_T && Math.sign(c) === sgn;
      }, 4);
      for (const [i0, i1] of rs) {
        // extend a little into the entry/exit like a real kerb does
        const a = i0 - 3, b = i1 + 3;
        const sub = [];
        for (let i = a; i <= b; i++) sub.push(i / RINGS);
        sweep(mb, spline, sub, (t, i, ramp) => {
          const w = spline.widthAt(t);
          const h = 0.16 * ramp;
          return [
            { l: sgn * (w - 0.05), h: 0.012, u: 0 },
            { l: sgn * (w + 0.16), h: h * 0.62, u: 0.12 },
            { l: sgn * (w + 1.35), h, u: 0.86 },
            { l: sgn * (w + 1.55), h: 0.0, u: 1.0 },
          ];
        }, { vScale: M.kerbLen, taper: 5 });
      }
    }
    if (mb.count) {
      const g = mb.geometry(); geos.push(g);
      const kerbs = new THREE.Mesh(g, kerbMat);
      kerbs.castShadow = !!q.shadows; kerbs.receiveShadow = !!q.shadows;
      kerbs.name = 'kerbs';
      group.add(kerbs);
    }
  }

  // =========================================================================
  // 4. RUN-OFF APRON — sand out to the wall line (physics wall = w + 5.5)
  // =========================================================================
  const RUNOFF = 5.5;
  const sandMaps = tileable(sandTexture({ size: S, tint: P.sandTint, ripple: def.theme === 'oasis' ? 1 : 0.35 }));
  const vergeMat = keep(stdMat(sandMaps, { vertexColors: true }));
  {
    const mb = new MB(true);
    for (const side of [-1, 1]) {
      sweep(mb, spline, ts, (t) => {
        const w = spline.widthAt(t);
        const n1 = fbm(noise, t * 90, side * 3.1, 3);
        const sec = [];
        const stops = [0.0, 0.10, 0.34, 0.68, 1.0];
        for (const f of stops) {
          const l = side * (w + f * RUNOFF);
          // dips away from the road so water/sand reads as run-off, not a shelf
          const h = -0.03 - Math.pow(f, 1.6) * (0.42 + n1 * 0.3);
          // darker, damper sand further out; a bleached strip right at the edge
          const k = lerp(1.12, 0.82, f) * (0.92 + n1 * 0.18);
          sec.push({ l, h, u: l / M.sand, col: [k, k * 0.98, k * 0.94] });
        }
        return sec;
      }, { vScale: M.sand, closed: true });
    }
    const g = mb.geometry(); geos.push(g);
    const verge = new THREE.Mesh(g, vergeMat);
    verge.receiveShadow = !!q.shadows;
    verge.name = 'runoff';
    group.add(verge);
  }

  // =========================================================================
  // 5. TERRAIN — carved so it can never poke through the road
  // =========================================================================
  const relief = (x, z) => {
    const a = fbm(noise, x * 0.0042, z * 0.0042, 4) - 0.5;
    const b = fbm(noise, x * 0.017 + 11, z * 0.017 - 7, 3) - 0.5;
    const c = fbm(noise, x * 0.055 - 3, z * 0.055 + 5, 2) - 0.5;
    return a * 30 + b * 6.5 + c * 1.4;
  };
  const FLAT = RUNOFF + 1.2, BLEND = 46;
  // פסגת הענן is not a plain: the circuit runs along the top of a stone plateau
  // that simply STOPS. Past ~58 m the ground falls 130 m into the cloud sea,
  // which is what makes the track read as floating rather than as a pale desert.
  const SKY_TRACK = def.theme === 'cloud';
  const reliefK = SKY_TRACK ? 0.22 : 1;
  // The edge has to be visible FROM THE ROAD or the track is just a pale plain:
  // flat for ~20 m past the barrier, then a sheer 60 m fall, then away into the
  // cloud sea. 
  const dropAt = (d, w) => (SKY_TRACK
    ? sstep(w + 21, w + 34, d) * 62 + sstep(w + 34, w + 150, d) * 260 : 0);
  const heightAt = (x, z) => {
    const s = spline.closestT(new THREE.Vector3(x, 0, z));
    const d = Math.abs(s.lateral);
    const w = spline.widthAt(s.t);
    const k = sstep(w + FLAT, w + BLEND, d);
    const base = s.pos.y - 0.55;
    return base + k * (relief(x, z) * reliefK + 3.2 * k) - dropAt(d, w);
  };
  {
    const b = spline.bounds;
    const cx = (b.minX + b.maxX) / 2, cz = (b.minZ + b.maxZ) / 2;
    const pad = 340;
    const sx = (b.maxX - b.minX) + pad * 2, sz = (b.maxZ - b.minZ) + pad * 2;
    const N = (q.propDensity >= 0.9 ? 168 : q.propDensity >= 0.6 ? 120 : 76) * (SKY_TRACK ? 1.5 : 1) | 0;
    const geo = new THREE.PlaneGeometry(sx, sz, N, N);
    geo.rotateX(-Math.PI / 2);
    const pos = geo.attributes.position;
    const col = new Float32Array(pos.count * 3);
    const v = new THREE.Vector3();
    for (let i = 0; i < pos.count; i++) {
      const x = pos.getX(i) + cx, z = pos.getZ(i) + cz;
      v.set(x, 0, z);
      const s = spline.closestT(v);
      const d = Math.abs(s.lateral);
      const w = spline.widthAt(s.t);
      const k = sstep(w + FLAT, w + BLEND, d);
      const y = s.pos.y - 0.55 + k * (relief(x, z) * reliefK + 3.2 * k) - dropAt(d, w);
      pos.setXYZ(i, pos.getX(i), y, pos.getZ(i));
      // tonal variation: ochre flats, redder on the rises, pale in the hollows
      const n = fbm(noise, x * 0.009 + 3, z * 0.009 - 2, 3);
      const rise = clamp01((y - s.pos.y) / 22);
      const r = lerp(0.86, 1.14, n) * lerp(1.0, 1.10, rise);
      if (SKY_TRACK) {
        // pale stone, going cooler and darker as the plateau falls away
        const fall = clamp01(-(y - s.pos.y) / 70);
        col[i * 3] = r * lerp(1.06, 0.62, fall);
        col[i * 3 + 1] = r * lerp(1.00, 0.62, fall);
        col[i * 3 + 2] = r * lerp(0.93, 0.78, fall);
      } else if (def.theme === 'circuit') {
        col[i * 3] = r * 0.94; col[i * 3 + 1] = r * 0.96; col[i * 3 + 2] = r * 1.06;
      } else {
        col[i * 3] = r * 1.02; col[i * 3 + 1] = r * 0.94; col[i * 3 + 2] = r * 0.84;
      }
    }
    geo.setAttribute('color', new THREE.Float32BufferAttribute(col, 3));
    geo.computeVertexNormals();
    geo.translate(cx, 0, cz);
    geos.push(geo);
    // Terrain is mostly seen at 60-400 m, so it gets its own low-contrast sand
    // at a much coarser tile (36 m): a road-scale tile out here turns into a
    // shimmering moire carpet, which is the other classic procedural tell.
    const groundMaps = tileable(SKY_TRACK
      ? rockTexture({ size: S, tint: P.dustTint, bands: 7, contrast: 0.22 })
      : sandTexture({ size: S, tint: P.dustTint, ripple: 0.25, seed: 91 }));
    const TILE = 36;
    const gmat = keep(new THREE.MeshStandardMaterial({
      map: groundMaps.map, roughness: 1, metalness: 0, vertexColors: true,
    }));
    gmat.map.repeat.set(sx / TILE, sz / TILE);
    gmat.map.offset.set(cx / TILE, cz / TILE);
    const ground = new THREE.Mesh(geo, gmat);
    ground.receiveShadow = !!q.shadows;
    ground.name = 'terrain';
    ground.renderOrder = -5;
    group.add(ground);
  }

  // =========================================================================
  // 6. BARRIERS — coursed sandstone blocks, with variation
  // =========================================================================
  const wallMaps = tileable(stoneWallTexture({
    size: S, tint: P.wall, mortar: P.wallMortar, rows: 3, cols: 4,
  }));
  const wallMat = keep(stdMat(wallMaps, { vertexColors: true, roughness: 0.95 }));
  {
    const mb = new MB(true);
    const TH = 0.62;
    for (const side of [-1, 1]) {
      sweep(mb, spline, ts, (t, i) => {
        const w = spline.widthAt(t);
        const n1 = fbm(noise, t * 130 + (side > 0 ? 40 : 0), side * 7, 3);
        const n2 = fbm(noise, t * 480, side * 2.5, 2);
        const h = 1.02 + n1 * 0.42;                    // 1.0 - 1.45 m
        const b = w + RUNOFF;                          // matches the physics wall
        const k = 0.86 + n1 * 0.26 + n2 * 0.10;        // per-ring block tone
        const col = [k, k * 0.985, k * 0.95];
        // inner face -> capstone -> outer face, uv.y = height/1.05 (3 courses)
        return [
          { l: side * b, h: -0.5, u: -0.5 / M.wallHigh, col },
          { l: side * b, h, u: h / M.wallHigh, col },
          { l: side * (b + TH * 0.5), h: h + 0.075, u: (h + 0.6) / M.wallHigh, col: [k * 1.1, k * 1.08, k * 1.04] },
          { l: side * (b + TH), h, u: (h + 1.2) / M.wallHigh, col },
          { l: side * (b + TH), h: -0.6, u: (h + 1.9) / M.wallHigh, col },
        ];
      }, { vScale: M.wallLen, swapUV: true, closed: true });
    }
    const g = mb.geometry(); geos.push(g);
    const wall = new THREE.Mesh(g, wallMat);
    wall.castShadow = !!q.shadows; wall.receiveShadow = !!q.shadows;
    wall.name = 'barrier';
    group.add(wall);
  }

  // A lit coping strip running the whole lap along the top of the barrier. On
  // the night circuit this single unbroken line of neon is what draws the shape
  // of the corner ahead out of the dark; on Cloud Peak it is a warm guide light.
  // One sweep, one unlit material, one draw call.
  if (def.theme === 'circuit' || def.theme === 'cloud') {
    const hot = def.theme === 'circuit' ? 0x36e0ff : 0xffd68a;
    const cool = def.theme === 'circuit' ? 0xff5fae : 0xffb0d0;
    const mb = new MB(true);
    const TH = 0.62;
    for (const side of [-1, 1]) {
      sweep(mb, spline, ts, (t, i) => {
        const w = spline.widthAt(t);
        const n1 = fbm(noise, t * 130 + (side > 0 ? 40 : 0), side * 7, 3);
        const h = 1.02 + n1 * 0.42 + 0.09;
        const b = w + RUNOFF;
        // colour drifts slowly between the two neons around the lap
        const mixk = 0.5 + 0.5 * Math.sin(t * Math.PI * 6 + (side > 0 ? 1.7 : 0));
        const c1 = new THREE.Color(hot).lerp(new THREE.Color(cool), mixk);
        const col = [c1.r, c1.g, c1.b];
        return [
          { l: side * (b - 0.04), h, u: 0, col },
          { l: side * (b + TH * 0.5), h: h + 0.02, u: 0.5, col },
          { l: side * (b + TH + 0.04), h, u: 1, col },
        ];
      }, { vScale: 4, swapUV: true, closed: true });
    }
    const g = mb.geometry(); geos.push(g);
    const m = new THREE.Mesh(g, keep(new THREE.MeshBasicMaterial({
      vertexColors: true, toneMapped: false, fog: true,
    })));
    m.name = 'neon-coping';
    group.add(m);
  }

  // =========================================================================
  // 7. CATCH FENCING on the outside of fast corners
  // =========================================================================
  const metalMaps = tileable(metalTexture({ size: Math.min(S, 512), tint: 0x9aa2ab }));
  const fenceMat = keep(stdMat(metalMaps, { color: 0x7d7f84, metalness: 0.45, roughness: 0.62 }));
  {
    const mb = new MB(false);
    const postGeo = new THREE.CylinderGeometry(0.07, 0.09, 2.45, 6);
    const posts = [];
    for (const sgn of [-1, 1]) {
      const rs = ranges(RINGS, i => {
        const c = curvOf(i);
        return Math.abs(c) > 0.135 && Math.sign(c) === -sgn;  // outside of the turn
      }, 6);
      for (const [i0, i1] of rs) {
        const sub = [];
        for (let i = i0 - 4; i <= i1 + 4; i++) sub.push(i / RINGS);
        // slim horizontal rails — catch fencing, not a motorway guardrail
        for (const [hy, th] of [[1.30, 0.035], [1.95, 0.035], [2.55, 0.055]]) {
          sweep(mb, spline, sub, (t, i, ramp) => {
            const w = spline.widthAt(t) + RUNOFF + 0.40;
            const y = hy * ramp + 0.9 * (1 - ramp);
            return [
              { l: sgn * (w - 0.05), h: y - th, u: 0 },
              { l: sgn * (w - 0.05), h: y + th, u: 0.5 },
              { l: sgn * (w + 0.05), h: y + th, u: 1 },
              { l: sgn * (w + 0.05), h: y - th, u: 0.5 },
            ];
          }, { vScale: 2.5, taper: 4 });
        }
        const step = Math.max(1, Math.round(3.2 / (L / RINGS)));
        for (let i = i0; i <= i1; i += step) {
          const t = ((i / RINGS) % 1 + 1) % 1;
          const fr = spline.frameAt(t);
          const w = spline.widthAt(t) + RUNOFF + 0.40;
          posts.push([fr.pos.x + fr.right.x * sgn * w, fr.pos.y + 1.35, fr.pos.z + fr.right.z * sgn * w]);
        }
      }
    }
    if (mb.count) {
      const g = mb.geometry(); geos.push(g);
      const rails = new THREE.Mesh(g, fenceMat);
      rails.castShadow = !!q.shadows;
      rails.name = 'fence-rails';
      group.add(rails);
    }
    if (posts.length) {
      geos.push(postGeo);
      const im = new THREE.InstancedMesh(postGeo, fenceMat, posts.length);
      const m4 = new THREE.Matrix4();
      posts.forEach((p, i) => { m4.makeTranslation(p[0], p[1], p[2]); im.setMatrixAt(i, m4); });
      im.instanceMatrix.needsUpdate = true;
      im.castShadow = !!q.shadows;
      im.name = 'fence-posts';
      group.add(im);
    } else postGeo.dispose();
  }

  // =========================================================================
  // 8. START / FINISH — chequer, gantry, flags
  // =========================================================================
  const startT = def.startT ?? 0;
  {
    const chequer = chequerTexture(128);
    chequer.wrapS = chequer.wrapT = THREE.RepeatWrapping;
    const chqMat = keep(new THREE.MeshStandardMaterial({
      map: chequer, roughness: 0.8, metalness: 0,
      polygonOffset: true, polygonOffsetFactor: -6, polygonOffsetUnits: -8,
    }));
    const mb = new MB(false);
    const wStart = spline.widthAt(startT);
    const dT = 1.9 / L;
    const rows = 8;
    for (let r = 0; r <= rows; r++) {
      const tt = startT - dT / 2 + (r / rows) * dT;
      const fr = spline.frameAt(((tt % 1) + 1) % 1);
      const base = mb.count;
      const cols = 2;
      for (let c = 0; c <= cols; c++) {
        const l = (c / cols * 2 - 1) * wStart;
        mb.vert(fr.pos.x + fr.right.x * l, fr.pos.y + 0.02, fr.pos.z + fr.right.z * l,
          l / (wStart * 2 / 6), r / rows * 1);      // 6 chequer tiles across
      }
      if (r > 0) {
        const prev = base - (cols + 1);
        for (let c = 0; c < cols; c++) mb.quad(prev + c, prev + c + 1, base + c + 1, base + c);
      }
    }
    const g = mb.geometry(); geos.push(g);
    const line = new THREE.Mesh(g, chqMat);
    line.name = 'startline';
    group.add(line);

    // --- gantry ------------------------------------------------------------
    const fr = spline.frameAt(startT);
    // The gantry is the first thing the player reads, so it wears the theme:
    // desert timber, a night-city steel truss, or pale plateau stone.
    const gantryMats = {
      oasis: () => stdMat(tileable(woodTexture({ size: Math.min(S, 512), tint: 0xb9884f })), { roughness: 0.92 }),
      circuit: () => stdMat(tileable(metalTexture({ size: Math.min(S, 512), tint: 0x7a828f })),
        { roughness: 0.42, metalness: 0.65, color: 0x59606e, emissive: 0x101a33, emissiveIntensity: 0.6 }),
      cloud: () => stdMat(tileable(stoneWallTexture({ size: Math.min(S, 512), tint: 0xece5dd, mortar: 0xc9c0b6, rows: 3, cols: 3 })),
        { roughness: 0.85, color: 0xf2ece4 }),
    };
    const woodMat = keep((gantryMats[def.theme] || gantryMats.oasis)());
    // the artwork lives in the top quarter of the (square) canvas, so the board
    // samples only that band — full texel density on a 4:1 banner
    const gTex = gantryTexture(def.nameHe, 1024, def.theme);
    gTex.repeat.set(1, 0.25); gTex.offset.set(0, 0.75);
    // FrontSide, one board per direction: a DoubleSide banner shows mirrored
    // Hebrew to anyone standing behind it.
    const gMat = keep(new THREE.MeshStandardMaterial({
      map: gTex, roughness: 0.75, side: THREE.FrontSide,
      emissiveMap: def.theme === 'oasis' ? null : gTex,
      emissive: def.theme === 'circuit' ? 0xffffff : def.theme === 'cloud' ? 0xffffff : 0x2a1a0c,
      emissiveIntensity: def.theme === 'circuit' ? 1.15 : def.theme === 'cloud' ? 0.5 : 0.35,
    }));

    const gan = new THREE.Group();
    gan.name = 'gantry';
    const span = wStart + RUNOFF + 1.4;   // legs stand outside the barrier
    const HGT = 6.2;
    // legs + cross-bracing, in one merged wooden geometry
    const wmb = new MB(false);
    for (const s of [-1, 1]) {
      wmb.box(s * span, HGT / 2, 0, 0.85, HGT, 0.85, 0.35);
      wmb.box(s * span, HGT + 0.35, 0, 1.3, 0.7, 1.3, 0.35);
      wmb.box(s * (span - 0.9), 1.1, 0, 2.1, 0.5, 0.55, 0.35);
      // diagonal-ish braces (as short boxes, rotated in the XZ plane is enough)
      wmb.box(s * span, HGT * 0.55, 0, 0.5, 3.4, 0.5, 0.35);
    }
    // the beam itself
    const beamW = span * 2 + 1.6;
    const boardH = Math.min(3.0, beamW / 9);
    wmb.box(0, HGT + 0.30, 0, beamW, 0.42, 1.35, 0.3);
    wmb.box(0, HGT + 0.60 + boardH, 0, beamW, 0.34, 1.35, 0.3);
    const wg = wmb.geometry(); geos.push(wg);
    const legs = new THREE.Mesh(wg, woodMat);
    legs.castShadow = !!q.shadows; legs.receiveShadow = !!q.shadows;
    gan.add(legs);

    const boardGeo = new THREE.PlaneGeometry(beamW - 0.3, boardH);
    geos.push(boardGeo);
    for (const side of [0, Math.PI]) {
      const board = new THREE.Mesh(boardGeo, gMat);
      // NAMED, and therefore swept by enforceSignOrientation and seen by the
      // gate. It was anonymous until Wave 4 round 2, which meant the single
      // piece of lettering D32 cites as the diagnostic ("the finish-line text is
      // fine") was the one piece neither the central guarantee nor the test
      // could see. It reads correctly only by construction — a PlaneGeometry
      // rotated by pi flips its normal and its U together — and "correct by
      // construction, unchecked" is precisely the seam this project keeps losing
      // days to.
      board.name = 'gantry-board';
      board.position.set(0, HGT + 0.45 + boardH / 2, side ? -0.14 : 0.14);
      board.rotation.y = side;
      board.castShadow = false;
      gan.add(board);
    }
    // pennants along the top of the beam, for silhouette
    {
      const flagCols = { oasis: [0xd94f3d, 0xf5ead6], circuit: [0x39e6ff, 0x1b2140, 0xff5fae, 0x1b2140],
        cloud: [0xffc247, 0xfdf4e6] }[def.theme] || [0xd94f3d, 0xf5ead6];
      const stripes = stripeTexture({ size: 128, colors: flagCols, count: 3 });
      const fmb = new MB(false);
      const nF = 6;
      for (let i = 0; i < nF; i++) {
        const x = (i / (nF - 1) - 0.5) * (beamW - 1.6);
        const y0 = HGT + 0.85 + boardH;
        const n0 = fmb.count;
        fmb.vert(x - 0.80, y0, 0, 0, 0); fmb.vert(x + 0.80, y0, 0, 1, 0);
        fmb.vert(x + 0.80, y0 + 1.75, 0, 1, 1); fmb.vert(x - 0.80, y0 + 1.75, 0, 0, 1);
        fmb.quad(n0, n0 + 1, n0 + 2, n0 + 3);
        fmb.box(x, y0 + 0.88, -0.06, 0.07, 1.8, 0.07, 1);
      }
      const fg = fmb.geometry(); geos.push(fg);
      const fmat = keep(new THREE.MeshStandardMaterial({ map: stripes, roughness: 0.9, side: THREE.DoubleSide }));
      const flags = new THREE.Mesh(fg, fmat);
      flags.castShadow = !!q.shadows;
      gan.add(flags);
    }
    // orient the gantry across the track: local +Z runs along the tangent, so
    // the legs (local +/-X) straddle the road.
    gan.position.copy(fr.pos);
    gan.rotation.y = Math.atan2(fr.tan.x, fr.tan.z);
    group.add(gan);
  }

  // =========================================================================
  // 8b. ROADSIDE SIGNAGE — the ambient curriculum
  // =========================================================================
  // Short AI-themed Hebrew boards, themed per track. Most of them sit in the
  // MID-GROUND band (15-34 m past the barrier), which is the depth rung GAPS.md
  // calls the highest-value visual fix left: at that distance a board is still
  // legible at racing speed but reads as scenery rather than as track furniture.
  // They thin with propDensity and, being at least 7 m outside the drivable
  // width, are structurally incapable of touching the racing line (the build
  // audit re-proves that anyway).
  //
  // SIZING, round 2: the mid boards are 11 x 2.75 m, not 7 x 3.5. The first pass
  // traded depth against legibility and lost the trade — pushing boards out to
  // 23-39 m while sizing them for arm's length put the Hebrew at 6.5-8 px of cap
  // height from the chase camera, i.e. texture rather than text. Because cap
  // height is `0.4 * boardWidth / characters`, a WIDER, SHORTER board with
  // SHORTER copy buys legibility without touching the placement, so the depth
  // rung survives intact. Pinned by the legibility gate in tests/signage.test.mjs.
  //
  // Deferred until after the dressing pass (section 10) so a board can be tested
  // against the props that would otherwise stand in front of it.

  /**
   * The props worth ray-testing a sign against: TALL enough to cross a board
   * (>3 m) and SMALL enough to trace cheaply (<20k triangles). That pair of
   * thresholds picks out exactly the lamp masts, marshal posts, paddock masts
   * and palms — the thin verticals that bisect a board — while excluding the
   * terrain and the cloud layer (six-figure triangle counts) and the barrier
   * (long, but knee-high, and every sign clears it by design). Deliberately
   * name-free: coupling this to props.js's internal mesh names would rot the
   * moment that file is reorganised, and rot silently.
   */
  function signOccluders() {
    const out = [];
    group.updateMatrixWorld(true);
    const box = new THREE.Box3();
    group.traverse(o => {
      if (!o.isMesh || !o.geometry || /^signage/.test(o.name)) return;
      const g = o.geometry;
      const tris = (g.index ? g.index.count : (g.attributes.position?.count || 0)) / 3;
      if (tris < 1 || tris > 20000) return;
      box.setFromObject(o);
      if (box.max.y - box.min.y < 3) return;
      out.push(o);
    });
    return out;
  }

  const _ray = new THREE.Raycaster();
  const _eye = new THREE.Vector3(), _dir = new THREE.Vector3();
  /**
   * Would a driver reading this board see a mast through the middle of it?
   * Probes the two spots the board is actually read from — roughly 45 m and 28 m
   * back up the racing line, at chase-camera eye height.
   */
  function signOccluded(occl, t, centre) {
    if (!occl.length) return false;
    for (const back of [45, 28]) {
      const rt = ((t - back / L) % 1 + 1) % 1;
      const rp = spline.offsetPoint(rt, 0);
      _eye.set(rp.x, rp.y + 3.25, rp.z);
      _dir.set(centre.x - _eye.x, centre.y - _eye.y, centre.z - _eye.z);
      const dist = _dir.length();
      if (dist < 1) continue;
      _ray.set(_eye, _dir.multiplyScalar(1 / dist));
      _ray.near = 0.5; _ray.far = dist - 1.0;
      if (_ray.intersectObjects(occl, false).length) return true;
    }
    return false;
  }

  const placeSignage = () => {
    const SIGNS = TRACK_SIGNS[def.theme] || TRACK_SIGNS.oasis;
    const density = q.propDensity ?? 1;
    // high 1.0 -> ~84 m apart, medium 0.7 -> ~122 m, low 0.35 -> ~210 m
    const step = density >= 0.9 ? 84 : density >= 0.6 ? 122 : 210;
    const nSign = Math.max(3, Math.round(L / step));
    const srng = makeRng(3300 + def.points.length * 17 + Math.round(L));
    const panels = new MB(false);
    const posts = new MB(false);
    // How far out the ground can actually carry a board. Cloud Peak's plateau
    // ends ~17 m past the barrier and then falls 20 m to the cloud sea, so the
    // outward search below tops out there — and that is the honest answer to
    // "Cloud Peak gets no depth rung": there is no mid-ground land to put one on.
    // What it gets instead is the plateau EDGE (see edgeSeek), which is scenery
    // no other track can have.
    const maxOut = SKY_TRACK ? 17 : 34;
    const occl = signOccluders();
    let placed = 0;
    for (let i = 0; i < nSign; i++) {
      const t = ((startT + (i + 0.5) / nSign + srng.range(-0.006, 0.006)) % 1 + 1) % 1;
      // keep the start/finish complex clear — the gantry is the read there
      if (Math.abs(((t - startT + 1.5) % 1) - 0.5) < 0.018) continue;
      const side = i % 2 === 0 ? 1 : -1;
      const w = spline.widthAt(t);
      // On the low tier only the mid-ground boards survive: they are the ones
      // doing the depth work, and the barrier already carries sponsor boards.
      const mid = density < 0.6 ? true : i % 3 !== 0;
      const pw = mid ? 13.0 : 6.8, ph = pw / SIGN_TILE_ASPECT;
      // Cloud Peak wants its boards ON the drop, standing against open sky; the
      // ground tracks want them spread through the mid-ground band for depth.
      //
      // THE BAND IS CAPPED BY THE FIELD OF VIEW, not by taste. A board `Y` metres
      // off the centreline leaves the 62-degree frame once the driver is closer
      // than ~0.93*Y along the track, so the largest it is ever seen at is
      // ~547 * capMetres / Y pixels. Round 1 scattered boards out to Y = 45 m,
      // where even a perfectly-sized board tops out at 12 px and then slides out
      // of frame — depth beyond about 34 m is depth nobody can read. So the band
      // is 8-18 m past the run-off (Y ~ 23-33 m): still unmistakably mid-ground,
      // still a rung above the barrier furniture, and now legible the whole way in.
      const wanted = !mid ? 1.8
        : SKY_TRACK ? Math.min(maxOut, srng.range(11, 17))
          : Math.min(maxOut, srng.range(8, 18));

      // Walk inward from the wanted distance until the ground is solid AND no
      // prop stands between the board and a driver reading it. Both used to be
      // "skip the sign", which is why the tracks quietly lost boards and why one
      // circuit board ended up bisected by a lamp mast.
      let put = null;
      for (const out of [wanted, wanted * 0.78, wanted * 0.58, wanted * 0.4, 1.8]) {
        const p = spline.offsetPoint(t, side * (w + RUNOFF + out));
        const gy = heightAt(p.x, p.z);
        if (gy < p.y - (mid ? 1.6 : 0.8)) continue;      // perched on the drop
        const bottom = mid ? (SKY_TRACK ? 4.2 : 3.0) : 1.9;
        const cy = gy + bottom + ph / 2;
        if (signOccluded(occl, t, { x: p.x, y: cy, z: p.z })) continue;
        put = { p, gy, cy };
        break;
      }
      if (!put) continue;
      const { p, gy, cy } = put;
      const tan = spline.tangentAt(t), right = spline.rightAt(t);
      // Face the centreline, angled back down the track so a driver arriving at
      // speed gets a square-on read rather than a sliver.
      const n = new THREE.Vector3(
        -side * right.x - 0.62 * tan.x, 0, -side * right.z - 0.62 * tan.z).normalize();
      addSignPanel(panels, { x: p.x, y: cy, z: p.z }, n, pw, ph, signUV(placed), 0.10);
      // legs, at the panel's own ends
      const U = signUAxis(n);
      const legH = cy + ph / 2 - gy;
      for (const s2 of [-1, 1]) {
        posts.box(p.x + U.x * s2 * pw * 0.40, gy + legH / 2, p.z + U.z * s2 * pw * 0.40,
          0.20, legH, 0.20, 0.8);
      }
      placed++;
    }
    if (panels.count) {
      const atlas = signAtlas(def.theme, Math.min(S, 512) * 2);
      const gP = panels.geometry(); geos.push(gP);
      const litK = (TRACK_SIGNS[def.theme] || TRACK_SIGNS.oasis).skin.lit;
      const sMesh = new THREE.Mesh(gP, keep(new THREE.MeshStandardMaterial({
        map: atlas, roughness: 0.78, metalness: 0, side: THREE.FrontSide,
        emissiveMap: litK ? atlas : null,
        emissive: litK ? 0xffffff : 0x000000, emissiveIntensity: litK,
      })));
      // FrontSide, and every face built from `up x N` — see the anti-mirroring
      // rule above. Two back-to-back faces, never one DoubleSide quad.
      sMesh.name = 'signage';
      sMesh.castShadow = false;
      sMesh.receiveShadow = !!q.shadows;
      group.add(sMesh);
      const gL = posts.geometry(); geos.push(gL);
      const legs2 = new THREE.Mesh(gL, fenceMat);
      legs2.name = 'signage-posts';
      legs2.castShadow = !!q.shadows;
      group.add(legs2);
    }
  };

  // =========================================================================
  // 9. CHECKPOINTS + TOKEN SPOTS
  // =========================================================================
  const CP = 16;
  const checkpoints = [];
  for (let i = 0; i < CP; i++) checkpoints.push(((startT + i / CP) % 1 + 1) % 1);

  // Smoothed racing line: hug the inside of corners, drift wide on entry/exit.
  const lineLat = new Float32Array(RINGS);
  for (let i = 0; i < RINGS; i++) {
    let c = 0;
    for (let k = -8; k <= 8; k++) c += spline.curvatureAt(((i + k) / RINGS % 1 + 1) % 1);
    c /= 17;
    const w = spline.widthAt(i / RINGS);
    lineLat[i] = Math.sign(c) * Math.min(1, Math.abs(c) / 0.22) * w * 0.52;
  }
  const tokenSpots = [];
  {
    const clusters = 8;
    for (let g2 = 0; g2 < clusters; g2++) {
      // sit the clusters just before the apex of the biggest corners and on the
      // fast straights, so they both reward the good line and bait a dive inside
      const t = ((startT + (g2 + 0.5) / clusters) % 1 + 1) % 1;
      const i = Math.floor(t * RINGS) % RINGS;
      const w = spline.widthAt(t);
      const corner = Math.min(1, Math.abs(spline.curvatureAt(t)) / 0.2);
      const centre = lerp(0, lineLat[i], corner);
      const spreads = corner > 0.4 ? [-0.34, 0, 0.34] : [-0.55, -0.18, 0.18, 0.55];
      for (const s of spreads) {
        const lat = clamp(centre + s * w, -w * 0.82, w * 0.82);
        const p = spline.offsetPoint(t, lat);
        p.y += 1.05;
        tokenSpots.push(p);
      }
    }
  }

  // =========================================================================
  // 10. SCENERY DRESSING
  // =========================================================================
  group.userData.heightAt = heightAt;
  group.userData.runoff = RUNOFF;
  group.userData.theme = def.theme;
  group.userData.palette = P;

  let dress = null;
  if (opts.dress !== false) {
    dress = dressTrack(group, spline, def, engine, makeRng(7700 + def.points.length));
  }

  // Signage last of all the world geometry: it is the only thing here that needs
  // to know what else is standing between it and the driver (see signOccluded).
  placeSignage();

  // CENTRAL ANTI-MIRRORING PASS. Runs on the FINISHED group — our own signage,
  // the dressing's barrier sponsor boards and the night city's holo billboards
  // all pass through here, so no module can reintroduce mirrored Hebrew by
  // getting its own placement maths backwards. See the rule near BRANDS.
  if (opts.signOrientation !== false) {
    group.userData.signOrientation = enforceSignOrientation(group, spline);
  }

  void metalMaps;

  const api = {
    group, spline, def, checkpoints, tokenSpots, heightAt, dress,
    update(time) { dress?.update?.(time); },
    dispose() {
      dress?.dispose?.();
      for (const g of geos) g.dispose?.();
      for (const m of mats) m.dispose?.();
      for (const d of disposables) d.dispose?.();
      group.traverse(o => { if (o.isInstancedMesh) o.dispose?.(); });
      group.clear();
    },
  };

  // GUARD (see auditTrackClearance): sweep the finished lap and shout if any
  // owned geometry stands in the drivable corridor. Nothing here has collision,
  // so anything that does is a wall karts drive through. ~30 ms, build-time
  // only, and it self-reports with the offending mesh's name.
  if (opts.audit !== false) auditTrackClearance(api, { throwOnFail: !!opts.strictAudit });

  return api;
}

function clamp(v, a, b) { return v < a ? a : v > b ? b : v; }

// ===========================================================================
// CLEARANCE AUDIT — the guard against "a wall lying across the track"
// ===========================================================================
//
// The physics only models two things laterally: the track limit at `widthAt(t)`
// and the barrier at `widthAt(t) + RUNOFF`. NOTHING else in the scene has
// collision. So any scenery mesh that ends up standing inside the drivable
// corridor is, by construction, a wall karts drive straight through — the exact
// class of bug that shipped on oasis (see DECISIONS/report).
//
// This sweeps every TRIANGLE we own and reports anything occupying the corridor:
//   |lateral| < widthAt(t) + MARGIN  AND  0.35 m < height above road < 4.6 m
//
// Triangles, not vertices: the mesa that shipped was a 7-sided prism with rings
// of vertices at its base (-11 m) and its top (+40 m) and nothing in between, so
// a vertex-only test walked straight past a 50 m wall standing on the road. Its
// FACES crossed the corridor; none of its points did.
//
// Ground-level furniture (paint, kerbs, run-off, the chequer) is below the floor
// of that volume and legitimately exempt; the gantry beam and the bunting are
// above its ceiling. Everything else is a bug.
const CORRIDOR = { floor: 0.35, ceil: 4.6, margin: 0.6, sample: 1.1 };
const AUDIT_SKIP = new Set(['road', 'paint', 'kerbs', 'runoff', 'terrain', 'startline']);

/**
 * Sweep the lap and assert that nothing we built stands in the drivable
 * corridor. Runs at build time on every track; O(triangles) thanks to a coarse
 * occupancy grid that rejects the ~99% of scenery that is nowhere near the road.
 *
 * @param {{group:THREE.Group, spline}} track  a buildTrack() result
 * @param {{throwOnFail?:boolean, log?:boolean}} opts
 * @returns {Array<{mesh,count,x,y,z,t,lateral,height}>} one entry per offending mesh
 */
export function auditTrackClearance(track, opts = {}) {
  const { group, spline } = track;
  const byMesh = new Map();
  const v = new THREE.Vector3();
  const a = new THREE.Vector3(), b = new THREE.Vector3(), c = new THREE.Vector3();
  const m4 = new THREE.Matrix4();
  group.updateMatrixWorld(true);

  // ---- coarse occupancy grid over the corridor ----------------------------
  // Marks every 6 m cell the road passes through, so a triangle's AABB can be
  // rejected with a handful of integer lookups instead of a closestT call.
  const CELL = 6;
  const bd = spline.bounds;
  const gw = Math.max(1, Math.ceil((bd.maxX - bd.minX) / CELL));
  const gh = Math.max(1, Math.ceil((bd.maxZ - bd.minZ) / CELL));
  const occ = new Uint8Array(gw * gh);
  const gx = x => Math.floor((x - bd.minX) / CELL);
  const gz = z => Math.floor((z - bd.minZ) / CELL);
  {
    const steps = Math.max(200, Math.round(spline.length));
    for (let i = 0; i < steps; i++) {
      const t = i / steps;
      const w = spline.widthAt(t) + CORRIDOR.margin;
      for (let l = -w; l <= w; l += CELL * 0.5) {
        const p = spline.offsetPoint(t, l);
        const cx = gx(p.x), cz = gz(p.z);
        for (let dx = -1; dx <= 1; dx++) for (let dz = -1; dz <= 1; dz++) {
          const ix = cx + dx, iz = cz + dz;
          if (ix >= 0 && ix < gw && iz >= 0 && iz < gh) occ[iz * gw + ix] = 1;
        }
      }
    }
  }
  const boxNearRoad = (x0, x1, z0, z1) => {
    const i0 = Math.max(0, gx(x0)), i1 = Math.min(gw - 1, gx(x1));
    const j0 = Math.max(0, gz(z0)), j1 = Math.min(gh - 1, gz(z1));
    if (i1 < i0 || j1 < j0) return false;
    for (let j = j0; j <= j1; j++) for (let i = i0; i <= i1; i++) if (occ[j * gw + i]) return true;
    return false;
  };

  const test = (name, x, y, z) => {
    v.set(x, 0, z);
    const s = spline.closestT(v);
    const lat = Math.abs(s.lateral);
    if (lat > spline.widthAt(s.t) + CORRIDOR.margin) return false;
    const h = y - s.pos.y;
    if (h < CORRIDOR.floor || h > CORRIDOR.ceil) return false;
    let rec = byMesh.get(name);
    if (!rec) {
      rec = { mesh: name, count: 0, worst: Infinity, x, y, z, t: s.t, lateral: s.lateral, height: h };
      byMesh.set(name, rec);
    }
    rec.count++;
    // "worst" = deepest inside the corridor, i.e. smallest |lateral|
    if (lat < rec.worst) {
      rec.worst = lat;
      rec.x = x; rec.y = y; rec.z = z; rec.t = s.t; rec.lateral = s.lateral; rec.height = h;
    }
    return true;
  };

  /** Sample a world-space triangle densely enough that no 1 m gap slips past. */
  const testTri = (name) => {
    // vertical reject first: a triangle entirely above or below the corridor
    // cannot cross it (the corridor floor/ceiling are measured from the road,
    // which is within a few metres of the triangle's own y where it matters).
    const minY = Math.min(a.y, b.y, c.y), maxY = Math.max(a.y, b.y, c.y);
    const x0 = Math.min(a.x, b.x, c.x), x1 = Math.max(a.x, b.x, c.x);
    const z0 = Math.min(a.z, b.z, c.z), z1 = Math.max(a.z, b.z, c.z);
    if (!boxNearRoad(x0, x1, z0, z1)) return;
    const n = Math.min(24, Math.max(2, Math.ceil(
      Math.max(x1 - x0, z1 - z0, maxY - minY) / CORRIDOR.sample)));
    for (let i = 0; i <= n; i++) {
      for (let j = 0; i + j <= n; j++) {
        const u = i / n, w2 = j / n, t2 = 1 - u - w2;
        test(name,
          a.x * t2 + b.x * u + c.x * w2,
          a.y * t2 + b.y * u + c.y * w2,
          a.z * t2 + b.z * u + c.z * w2);
      }
    }
  };

  group.traverse(o => {
    if (!o.isMesh || AUDIT_SKIP.has(o.name)) return;
    // Additive light cards that never write depth cannot read as an obstruction
    // — a pool of neon lying on the wet tarmac is the point, not a bug.
    const mm = Array.isArray(o.material) ? o.material[0] : o.material;
    if (mm && mm.transparent && mm.depthWrite === false) return;
    const geo = o.geometry;
    const pos = geo?.attributes?.position;
    if (!pos) return;
    if (!geo.boundingBox) geo.computeBoundingBox();
    const label = o.name || 'unnamed:' + geo.uuid.slice(0, 6);
    const idx = geo.index;
    const triCount = idx ? idx.count / 3 : pos.count / 3;
    const n = o.isInstancedMesh ? o.count : 1;
    const bb = new THREE.Box3();
    for (let k = 0; k < n; k++) {
      if (o.isInstancedMesh) { o.getMatrixAt(k, m4); m4.premultiply(o.matrixWorld); }
      else m4.copy(o.matrixWorld);
      // whole-instance reject
      bb.copy(geo.boundingBox).applyMatrix4(m4);
      if (!boxNearRoad(bb.min.x, bb.max.x, bb.min.z, bb.max.z)) continue;
      for (let f = 0; f < triCount; f++) {
        const i0 = idx ? idx.getX(f * 3) : f * 3;
        const i1 = idx ? idx.getX(f * 3 + 1) : f * 3 + 1;
        const i2 = idx ? idx.getX(f * 3 + 2) : f * 3 + 2;
        a.set(pos.getX(i0), pos.getY(i0), pos.getZ(i0)).applyMatrix4(m4);
        b.set(pos.getX(i1), pos.getY(i1), pos.getZ(i1)).applyMatrix4(m4);
        c.set(pos.getX(i2), pos.getY(i2), pos.getZ(i2)).applyMatrix4(m4);
        testTri(label);
      }
    }
  });

  const hits = [...byMesh.values()];
  if (opts.log !== false && hits.length && typeof console !== 'undefined') {
    for (const h of hits) {
      console.error(`[track ${track.def?.id}] CORRIDOR VIOLATION: mesh "${h.mesh}" (${h.count} samples), ` +
        `deepest at (${h.x.toFixed(1)}, ${h.y.toFixed(1)}, ${h.z.toFixed(1)}) — t=${h.t.toFixed(4)} ` +
        `lateral=${h.lateral.toFixed(2)} height=${h.height.toFixed(2)}`);
    }
  }
  if (opts.throwOnFail && hits.length) {
    throw new Error(`track ${track.def?.id}: ${hits.length} mesh(es) inside the drivable corridor: ` +
      hits.map(h => h.mesh).join(', '));
  }
  return hits;
}

// ===========================================================================
// PREVIEWS
// ===========================================================================

function baseScene(engine, trackId = 'oasis') {
  const scene = new THREE.Scene();
  const { def } = getTrack(trackId);
  const rig = applyTheme(scene, def.theme, engine);
  const track = buildTrack(trackId, engine);
  scene.add(track.group);
  const camera = new THREE.PerspectiveCamera(58, 16 / 9, 0.15, 3000);
  return { scene, camera, rig, track, def };
}

function wrap(engine, ctx, place) {
  const { scene, camera, rig, track } = ctx;
  place(camera, track, rig);
  let t = 0;
  return {
    scene, camera, rig, track,
    update(dt) {
      t += dt;
      track.update(t);
      rig.update(dt, camera);
    },
    resize(w, h) { camera.aspect = w / h; camera.updateProjectionMatrix(); },
    dispose() {
      track.dispose();
      rig.dispose();
      disposeTextureCache();
    },
  };
}

/**
 * Driver's-eye view from just behind the start line, looking down the track —
 * the A/B frame against the reference art.
 */
export function preview(engine) { return previewFor(engine, 'oasis'); }
/** Same framing on עיר הנוירונים — the neon night city. */
export function previewCircuit(engine) { return previewFor(engine, 'circuit'); }
/** Same framing on פסגת הענן — dawn above the clouds. */
export function previewCloud(engine) { return previewFor(engine, 'cloud'); }

function previewFor(engine, id) {
  const ctx = baseScene(engine, id);
  return wrap(engine, ctx, (camera, track, rig) => {
    const sp = track.spline, def = track.def;
    // Framed to match reference/image4.png: driver eye height, road filling the
    // lower half, the gantry sitting just inside the top edge rather than
    // hanging over the lens.
    const t0 = ((def.startT - 42 / sp.length) % 1 + 1) % 1;
    const p = sp.offsetPoint(t0, 0.8);
    camera.position.set(p.x, p.y + 2.05, p.z);
    const look = sp.offsetPoint(((def.startT + 90 / sp.length) % 1 + 1) % 1, -0.6);
    camera.lookAt(look.x, look.y + 5.2, look.z);
    rig.setShadowFocus(p);
  });
}

/** Sitting on the grid, right under the gantry — the pre-race hero shot. */
export function previewGrid(engine) {
  const ctx = baseScene(engine, 'oasis');
  return wrap(engine, ctx, (camera, track, rig) => {
    const sp = track.spline, def = track.def;
    const t0 = ((def.startT - 13 / sp.length) % 1 + 1) % 1;
    const p = sp.offsetPoint(t0, 0.8);
    camera.position.set(p.x, p.y + 1.55, p.z);
    const look = sp.offsetPoint(((def.startT + 55 / sp.length) % 1 + 1) % 1, -0.6);
    camera.lookAt(look.x, look.y + 3.6, look.z);
    rig.setShadowFocus(p);
  });
}

/** High wide shot showing the whole circuit layout. */
export function previewAerial(engine) { return previewAerialFor(engine, 'oasis'); }
export function previewAerialCircuit(engine) { return previewAerialFor(engine, 'circuit'); }
export function previewAerialCloud(engine) { return previewAerialFor(engine, 'cloud'); }

function previewAerialFor(engine, id) {
  const ctx = baseScene(engine, id);
  return wrap(engine, ctx, (camera, track, rig) => {
    const b = track.spline.bounds;
    const cx = (b.minX + b.maxX) / 2, cz = (b.minZ + b.maxZ) / 2;
    const r = Math.max(b.maxX - b.minX, b.maxZ - b.minZ);
    camera.fov = 46; camera.updateProjectionMatrix();
    camera.position.set(cx + r * 0.30, r * 0.72, cz + r * 0.78);
    camera.lookAt(cx, 0, cz - r * 0.02);
    // a wide layout shot needs to see the layout: thin the haze right down
    rig.fog.density *= 0.16;
    rig.setShadowFocus(new THREE.Vector3(cx, 0, cz));
  });
}

/** Three-quarter view of a dressed corner: kerbs, barrier, crowd. */
export function previewCorner(engine) { return previewCornerFor(engine, 'oasis'); }
export function previewCornerCircuit(engine) { return previewCornerFor(engine, 'circuit'); }
export function previewCornerCloud(engine) { return previewCornerFor(engine, 'cloud'); }

function previewCornerFor(engine, id) {
  const ctx = baseScene(engine, id);
  return wrap(engine, ctx, (camera, track, rig) => {
    const sp = track.spline;
    // find the tightest corner
    let best = 0, bestC = 0;
    for (let i = 0; i < 400; i++) {
      const t = i / 400;
      // stay away from the start/finish complex — that is preview()'s job
      const d = Math.min(Math.abs(t - track.def.startT), 1 - Math.abs(t - track.def.startT));
      if (d < 0.18) continue;
      const c = Math.abs(sp.curvatureAt(t));
      if (c > bestC) { bestC = c; best = t; }
    }
    const apexT = ((best - 30 / sp.length) % 1 + 1) % 1;
    const sgn = Math.sign(sp.curvatureAt(best)) || 1;   // outside of the corner
    const w = sp.widthAt(apexT);
    // Framed like reference/image5.png: sitting on the racing line at corner
    // entry, kerb and barrier sweeping past on the inside.
    // Corner entry on the outside, aimed straight at the apex kerb 20 m away —
    // the kerb, its barrier and the crowd behind it fill the middle of frame.
    // Framed like reference/image5.png: running the inside line into the apex,
    // so the kerb, its barrier and the crowd behind sweep past down one side of
    // frame instead of sitting as a dot in the middle distance.
    // Framed like reference/image5.png: corner entry from the outside line,
    // aimed squarely at the apex kerb 30 m ahead, so kerb, barrier and crowd
    // occupy the middle of frame rather than the edge of it.
    const eye = sp.offsetPoint(apexT, -sgn * (w * 0.85));
    const look = sp.offsetPoint(best, sgn * (w + 0.8));
    camera.fov = 54; camera.updateProjectionMatrix();
    camera.position.set(eye.x, eye.y + 1.60, eye.z);
    camera.lookAt(look.x, look.y + 0.85, look.z);
    rig.setShadowFocus(look);
  });
}
