// Track meshing: turns a TrackSpline into an actual racetrack you can look at.
//
// Everything here is generated by sweeping cross-sections along the spline's
// arc-length-uniform `t`, so road, edge lines, kerbs, run-off, barriers and
// fencing all agree with the physics (which uses `widthAt(t)` for the track
// limit and `widthAt(t) + 5.5` for the wall).
//
//   const track = buildTrack('oasis', engine);
//   scene.add(track.group);
//   track.checkpoints  -> ordered t values for lap validation
//   track.tokenSpots   -> world positions where the race spawns pickups
//
// Draw-call discipline: every sweep of the same material is accumulated into a
// SINGLE merged geometry (left + right sides, all corners, the whole lap), so
// the bare track is ~10 draw calls before scenery dressing.
import * as THREE from 'three';
import { getTrack, gridSlots } from './trackdef.js';
import { makeRng, makeNoise2D, fbm } from '../core/rng.js';
import {
  asphaltTexture, sandTexture, rockTexture, stoneWallTexture, curbTexture,
  metalTexture, woodTexture, stripeTexture, canvasTexture, disposeTextureCache,
} from '../gfx/textures.js';
import { applyTheme, getTheme } from '../gfx/sky.js';
import { dressTrack } from '../gfx/props.js';

const clamp01 = v => (v < 0 ? 0 : v > 1 ? 1 : v);
const smooth = t => t * t * (3 - 2 * t);
const sstep = (a, b, x) => smooth(clamp01((x - a) / (b - a || 1e-6)));
const lerp = (a, b, t) => a + (b - a) * t;

// Real-world texture scale, in metres per texture tile. Getting these wrong is
// the classic procedural-track tell: asphalt aggregate that reads as gravel the
// size of footballs, or kerb stripes three metres long.
const M = {
  asphalt: 3.0,      // 3 m of aggregate per tile
  sand: 6.0,
  kerbLen: 1.6,      // 2 stripes per tile -> 0.8 m stripes (real kerbs are ~0.5-1 m)
  wallLen: 4.0,      // 4 blocks per tile -> 1.0 m blocks
  wallHigh: 1.05,    // 3 courses per tile -> 0.35 m courses
};

// ---------------------------------------------------------------------------
// tiny mesh builder — merged geometry without pulling in an addon
// ---------------------------------------------------------------------------

class MB {
  constructor(useColor = false) {
    this.p = []; this.uv = []; this.c = []; this.i = []; this.useColor = useColor;
  }
  get count() { return this.p.length / 3; }
  vert(x, y, z, u, v, col) {
    this.p.push(x, y, z); this.uv.push(u, v);
    if (this.useColor) this.c.push(col ? col[0] : 1, col ? col[1] : 1, col ? col[2] : 1);
  }
  tri(a, b, c) { this.i.push(a, b, c); }
  quad(a, b, c, d) { this.i.push(a, b, d, b, c, d); }
  /** Append an axis-aligned box (used for gantry legs, plinths, kerb caps…). */
  box(cx, cy, cz, sx, sy, sz, uScale = 1, col = null, rotY = 0) {
    const co = Math.cos(rotY), si = Math.sin(rotY);
    const hx = sx / 2, hy = sy / 2, hz = sz / 2;
    const corners = [
      [-hx, -hy, -hz], [hx, -hy, -hz], [hx, hy, -hz], [-hx, hy, -hz],
      [-hx, -hy, hz], [hx, -hy, hz], [hx, hy, hz], [-hx, hy, hz],
    ].map(([x, y, z]) => [cx + x * co - z * si, cy + y, cz + x * si + z * co]);
    const faces = [
      [0, 1, 2, 3, sx, sy], [5, 4, 7, 6, sx, sy], [4, 0, 3, 7, sz, sy],
      [1, 5, 6, 2, sz, sy], [3, 2, 6, 7, sx, sz], [4, 5, 1, 0, sx, sz],
    ];
    for (const [a, b, c, d, fu, fv] of faces) {
      const n = this.count;
      const uvs = [[0, 0], [fu * uScale, 0], [fu * uScale, fv * uScale], [0, fv * uScale]];
      [a, b, c, d].forEach((vi, k) => this.vert(corners[vi][0], corners[vi][1], corners[vi][2], uvs[k][0], uvs[k][1], col));
      this.quad(n, n + 1, n + 2, n + 3);
    }
  }
  geometry(flat = false) {
    const g = new THREE.BufferGeometry();
    g.setAttribute('position', new THREE.Float32BufferAttribute(this.p, 3));
    g.setAttribute('uv', new THREE.Float32BufferAttribute(this.uv, 2));
    if (this.useColor) g.setAttribute('color', new THREE.Float32BufferAttribute(this.c, 3));
    g.setIndex(this.i);
    g.computeVertexNormals();
    if (flat) g.computeVertexNormals();
    g.computeBoundingSphere();
    return g;
  }
}

/**
 * Sweep a cross-section along the spline.
 *
 * @param mb          target MeshBuilder
 * @param spline      TrackSpline
 * @param ts          array of (possibly >1, monotonically increasing) lap fractions
 * @param sectionFn   (t, i, ramp, frame) -> [{l, h, u, col?}]  l = lateral (m),
 *                    h = height above the banked road plane (m), u = cross-section
 *                    texture coordinate
 * @param opts.vScale metres per texture tile along the track
 * @param opts.swapUV true -> uv = (alongTrack, u) instead of (u, alongTrack)
 * @param opts.taper  number of rings at each end over which `ramp` fades 0..1
 */
function sweep(mb, spline, ts, sectionFn, opts = {}) {
  const { vScale = 4, swapUV = false, taper = 0, closed = false } = opts;
  const n = ts.length;
  const R = new THREE.Vector3(), U = new THREE.Vector3();
  let prevBase = -1, cols = 0;
  for (let i = 0; i < n; i++) {
    const t = ts[i];
    const fr = spline.frameAt(((t % 1) + 1) % 1);
    const cb = Math.cos(fr.bank), sb = Math.sin(fr.bank);
    R.set(fr.right.x * cb + fr.up.x * sb, fr.right.y * cb + fr.up.y * sb, fr.right.z * cb + fr.up.z * sb);
    U.set(fr.up.x * cb - fr.right.x * sb, fr.up.y * cb - fr.right.y * sb, fr.up.z * cb - fr.right.z * sb);
    let ramp = 1;
    if (taper > 0 && !closed) ramp = Math.min(smooth(clamp01(i / taper)), smooth(clamp01((n - 1 - i) / taper)));
    const sec = sectionFn(t, i, ramp, fr);
    cols = sec.length;
    const arc = t * spline.length;
    const base = mb.count;
    for (const s of sec) {
      const x = fr.pos.x + R.x * s.l + U.x * s.h;
      const y = fr.pos.y + R.y * s.l + U.y * s.h;
      const z = fr.pos.z + R.z * s.l + U.z * s.h;
      const av = arc / vScale;
      if (swapUV) mb.vert(x, y, z, av, s.u, s.col);
      else mb.vert(x, y, z, s.u, av, s.col);
    }
    if (prevBase >= 0) {
      for (let c = 0; c < cols - 1; c++) {
        mb.quad(prevBase + c, prevBase + c + 1, base + c + 1, base + c);
      }
    }
    prevBase = base;
  }
}

/** Evenly spaced lap fractions, `count` of them, starting at 0. */
function lapTs(count) {
  const ts = new Array(count + 1);
  for (let i = 0; i <= count; i++) ts[i] = i / count;
  return ts;
}

/** Contiguous index ranges where predicate(i) holds, on a circular domain. */
function ranges(n, predicate, minLen = 3) {
  const flag = new Array(n);
  for (let i = 0; i < n; i++) flag[i] = predicate(i);
  // rotate so we always start at a false->true edge (handles wrap-around)
  let start = 0;
  while (start < n && flag[start]) start++;
  if (start === n) return [[0, n - 1]];
  const out = [];
  let i = 0, cur = null;
  for (let k = 0; k < n; k++) {
    i = (start + k) % n;
    if (flag[i]) { if (!cur) cur = [start + k, start + k]; else cur[1] = start + k; }
    else if (cur) { if (cur[1] - cur[0] + 1 >= minLen) out.push(cur); cur = null; }
  }
  if (cur && cur[1] - cur[0] + 1 >= minLen) out.push(cur);
  return out;
}

function stdMat(maps, extra = {}) {
  return new THREE.MeshStandardMaterial({
    map: maps.map || null, normalMap: maps.normalMap || null,
    roughnessMap: maps.roughnessMap || null, roughness: 1, metalness: 0, ...extra,
  });
}

/** All maps in a bundle wrap and tile 1:1 (our UVs are already in tile units). */
function tileable(maps) {
  for (const t of Object.values(maps)) {
    if (t?.isTexture) { t.wrapS = t.wrapT = THREE.RepeatWrapping; t.repeat.set(1, 1); }
  }
  return maps;
}

// ---------------------------------------------------------------------------
// signage — our own invented in-world Hebrew brands
// ---------------------------------------------------------------------------

export const BRANDS = [
  { he: 'טורבו־בינה', bg: 0xc4402f, fg: 0xffe9c4 },
  { he: 'מנוע פרומפט', bg: 0x1f6f78, fg: 0xfdf3dd },
  { he: 'ברק אנרגיה', bg: 0xe0a52c, fg: 0x3a2410 },
  { he: 'נחל נתונים', bg: 0x2f5f34, fg: 0xf2f6d8 },
  { he: 'אלגו־גיר', bg: 0x6b3f8c, fg: 0xf7e6ff },
  { he: 'שמן חכם', bg: 0xb4552a, fg: 0xffe6bf },
];

function hexCss(h) { return '#' + h.toString(16).padStart(6, '0'); }

/** A sponsor board / banner face. Cached by brand index + size. */
export function brandTexture(index, size = 256) {
  const b = BRANDS[index % BRANDS.length];
  return canvasTexture(`brand${index % BRANDS.length}`, size, (ctx, S) => {
    const H = S / 4;
    ctx.fillStyle = hexCss(b.bg);
    ctx.fillRect(0, 0, S, S);
    // faded canvas weave so the board is not a flat colour
    for (let i = 0; i < 900; i++) {
      const x = (i * 97) % S, y = (i * 181) % S;
      ctx.fillStyle = `rgba(255,255,255,${0.012 + ((i * 13) % 7) * 0.004})`;
      ctx.fillRect(x, y, 3, 2);
    }
    ctx.fillStyle = hexCss(b.fg);
    ctx.globalAlpha = 0.22;
    ctx.fillRect(0, S * 0.06, S, S * 0.02);
    ctx.fillRect(0, S * 0.92, S, S * 0.02);
    ctx.globalAlpha = 1;
    ctx.direction = 'rtl';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.font = `bold ${Math.round(S * 0.19)}px "Arial Hebrew", "Noto Sans Hebrew", sans-serif`;
    ctx.fillStyle = 'rgba(0,0,0,0.28)';
    ctx.fillText(b.he, S / 2 + S * 0.008, S / 2 + S * 0.012);
    ctx.fillStyle = hexCss(b.fg);
    ctx.fillText(b.he, S / 2, S / 2);
    void H;
  }, { wrap: THREE.RepeatWrapping });
}

/** The start gantry face: track name + a couple of brand strips. */
function gantryTexture(nameHe, size = 512) {
  return canvasTexture('gantry:' + nameHe, size, (ctx, S) => {
    const H = S / 4;                       // the beam is 4:1
    const g = ctx.createLinearGradient(0, 0, 0, H);
    g.addColorStop(0, '#3a2418'); g.addColorStop(0.5, '#5c3a22'); g.addColorStop(1, '#2c1a11');
    ctx.fillStyle = '#1a1410'; ctx.fillRect(0, 0, S, S);
    ctx.fillStyle = g; ctx.fillRect(0, 0, S, H);
    // gold rule lines
    ctx.fillStyle = '#ffc247';
    ctx.fillRect(0, H * 0.06, S, H * 0.035);
    ctx.fillRect(0, H * 0.90, S, H * 0.035);
    ctx.direction = 'rtl'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
    ctx.font = `bold ${Math.round(H * 0.48)}px "Arial Hebrew", "Noto Sans Hebrew", sans-serif`;
    ctx.fillStyle = 'rgba(0,0,0,0.45)';
    ctx.fillText(nameHe, S / 2, H * 0.53 + H * 0.02);
    ctx.fillStyle = '#ffd98a';
    ctx.fillText(nameHe, S / 2, H * 0.51);
    // lamp strip along the bottom
    const lamps = 26;
    for (let i = 0; i < lamps; i++) {
      const x = (i + 0.5) / lamps * S;
      const r = H * 0.045;
      const rg = ctx.createRadialGradient(x, H * 0.965, 0, x, H * 0.965, r * 2.6);
      rg.addColorStop(0, 'rgba(255,246,214,0.95)'); rg.addColorStop(1, 'rgba(255,200,110,0)');
      ctx.fillStyle = rg; ctx.beginPath(); ctx.arc(x, H * 0.965, r * 2.6, 0, 7); ctx.fill();
    }
  });
}

/** Chequered flag pattern for the start/finish line. */
function chequerTexture(size = 128) {
  return canvasTexture('chequer', size, (ctx, S) => {
    const n = 8;
    for (let y = 0; y < n; y++) {
      for (let x = 0; x < n; x++) {
        const on = (x + y) % 2 === 0;
        ctx.fillStyle = on ? '#eceae2' : '#22211f';
        ctx.fillRect(x * S / n, y * S / n, S / n + 1, S / n + 1);
        // scuff so it is not a perfect vector checker
        ctx.fillStyle = `rgba(${on ? '90,86,78' : '210,206,196'},${0.03 + ((x * 7 + y * 3) % 5) * 0.012})`;
        ctx.fillRect(x * S / n, y * S / n, S / n, S / n);
      }
    }
  }, { wrap: THREE.RepeatWrapping });
}

// ---------------------------------------------------------------------------
// buildTrack
// ---------------------------------------------------------------------------

/**
 * Build the full track mesh set for a track id (or index).
 *
 * @returns {{group:THREE.Group, spline, def, checkpoints:number[],
 *            tokenSpots:THREE.Vector3[], heightAt:(x,z)=>number,
 *            dress:object|null, update:(t)=>void, dispose:()=>void}}
 */
export function buildTrack(idOrIndex, engine, opts = {}) {
  const { def, spline } = getTrack(idOrIndex);
  const q = engine?.q || { texSize: 1024, shadows: true, propDensity: 1, crowdDensity: 1, drawDistance: 700 };
  const theme = getTheme(def.theme);
  const S = q.texSize;
  const rng = makeRng(1000 + def.id.length * 37 + def.points.length);
  const noise = makeNoise2D(4400 + def.laps * 13);

  const group = new THREE.Group();
  group.name = 'track:' + def.id;
  const geos = [], mats = [], disposables = [];
  const keep = (m) => { mats.push(m); return m; };

  const L = spline.length;
  const detail = q.propDensity >= 0.9 ? 1 : q.propDensity >= 0.6 ? 0.72 : 0.5;
  const RINGS = Math.max(180, Math.round(L / (2.0 / detail)));   // ~2 m per ring at high
  const ts = lapTs(RINGS);

  // ---- palettes per theme (oasis is the Wave-1 flagship) -------------------
  const P = {
    oasis: {
      asphalt: 0x4a4744, sandTint: 0xd8ae6f, dustTint: 0xc79a5f,
      wall: 0xd3b083, wallMortar: 0x9a7f5c, rock: 0xa9603a,
      kerbA: 0xc23026, kerbB: 0xf0e6d6, paint: 0xe9e3d2,
    },
    circuit: {
      asphalt: 0x3b3e46, sandTint: 0x5a5f63, dustTint: 0x4a4e55,
      wall: 0x6f7480, wallMortar: 0x4a4e57, rock: 0x4a4458,
      kerbA: 0xbe2b58, kerbB: 0xe8e4ee, paint: 0xdfe6f2,
    },
    cloud: {
      asphalt: 0x585b63, sandTint: 0xc9c6cf, dustTint: 0xb9b6c2,
      wall: 0xd7d2dd, wallMortar: 0xa39fae, rock: 0x8e8c9e,
      kerbA: 0xc44a6e, kerbB: 0xf6f2f6, paint: 0xf2eee6,
    },
  }[def.theme] || {};

  // =========================================================================
  // 1. ROAD
  // =========================================================================
  // At 256 px the aggregate is drawn at ~4x the pixel density of the 1024 map,
  // so a 3 m tile turns the low tier into cobblestones. Scale the tile with the
  // texture instead of hard-coding it.
  const asphaltTile = M.asphalt * (S >= 512 ? 1 : 1.6);
  const asph = tileable(asphaltTexture({ size: S, tint: P.asphalt, wetness: def.theme === 'circuit' ? 0.85 : 0 }));
  const roadMat = keep(stdMat(asph, {
    metalness: def.theme === 'circuit' ? 0.22 : 0.0,
    vertexColors: true,
    // The aggregate height field is authored for a 1024 map. At 256 the same
    // normals cover 4x the area each and the road turns into cobbles, so the
    // low tier keeps the albedo grain and drops most of the relief.
    normalScale: new THREE.Vector2(1, 1).multiplyScalar(S >= 512 ? 1 : 0.4),
  }));
  {
    const mb = new MB(true);
    const COLS = 8;                                   // 9 columns across
    sweep(mb, spline, ts, (t) => {
      const w = spline.widthAt(t);
      const sec = [];
      // faint tyre-polished lanes: two darker bands where the racing line runs
      for (let c = 0; c <= COLS; c++) {
        const f = c / COLS * 2 - 1;                   // -1..1
        const l = f * w;
        const lane = Math.exp(-Math.pow((Math.abs(f) - 0.42) / 0.20, 2));
        const dirt = 1 - sstep(0.72, 1.0, Math.abs(f)) * 0.16;   // grubbier at the edges
        const k = (1 - lane * 0.10) * dirt;
        sec.push({ l, h: 0, u: l / asphaltTile, col: [k, k * 0.995, k * 0.985] });
      }
      return sec;
    }, { vScale: asphaltTile, closed: true });
    const g = mb.geometry(); geos.push(g);
    const road = new THREE.Mesh(g, roadMat);
    road.receiveShadow = !!q.shadows;
    road.name = 'road';
    group.add(road);
  }

  // =========================================================================
  // 2. WHITE PAINT — edge lines, start line box, grid markings
  // =========================================================================
  const paintMat = keep(new THREE.MeshStandardMaterial({
    color: P.paint, roughness: 0.82, metalness: 0,
    polygonOffset: true, polygonOffsetFactor: -4, polygonOffsetUnits: -6,
  }));
  {
    const mb = new MB(false);
    for (const side of [-1, 1]) {
      sweep(mb, spline, ts, (t) => {
        const w = spline.widthAt(t);
        const a = side * (w - 0.42), b = side * (w - 0.10);
        return [{ l: Math.min(a, b), h: 0.015, u: 0 }, { l: Math.max(a, b), h: 0.015, u: 1 }];
      }, { vScale: 2, closed: true });
    }
    // starting grid boxes — two columns, four rows behind the line
    const slots = gridSlots(spline, def, 8);
    const BW = 1.05, BL = 2.4, TH = 0.14;
    for (const s of slots) {
      const fr = spline.frameAt(s.t);
      const dAlong = BL / L;
      // 3 sides of an open box (the front edge stays open, like the reference)
      const parts = [
        [s.lateral - BW, s.lateral - BW + TH, -dAlong, dAlong],
        [s.lateral + BW - TH, s.lateral + BW, -dAlong, dAlong],
        [s.lateral - BW, s.lateral + BW, -dAlong, -dAlong + TH / L * 6],
      ];
      for (const [l0, l1, t0, t1] of parts) {
        const n = mb.count;
        const corners = [[l0, t0], [l1, t0], [l1, t1], [l0, t1]];
        for (const [l, dt] of corners) {
          const f2 = spline.frameAt(((s.t + dt) % 1 + 1) % 1);
          mb.vert(f2.pos.x + f2.right.x * l, f2.pos.y + 0.016, f2.pos.z + f2.right.z * l, 0, 0);
        }
        mb.quad(n, n + 1, n + 2, n + 3);
      }
      void fr;
    }
    const g = mb.geometry(); geos.push(g);
    const paint = new THREE.Mesh(g, paintMat);
    paint.receiveShadow = false;
    paint.name = 'paint';
    group.add(paint);
  }

  // =========================================================================
  // 3. KERBS — corners only, on the inside of the turn
  // =========================================================================
  const kerbMaps = tileable(curbTexture({
    size: Math.min(S, 512), colorA: P.kerbA, colorB: P.kerbB, stripes: 2, wear: 0.6, axis: 'v',
  }));
  const kerbMat = keep(stdMat(kerbMaps, { roughness: 0.85 }));
  const curvOf = i => spline.curvatureAt(ts[i % RINGS]);
  {
    const mb = new MB(false);
    const KERB_T = 0.055;                    // ~R < 200 m counts as a corner
    for (const sgn of [-1, 1]) {
      // sgn is the side of the road the kerb sits on, and a kerb belongs on the
      // INSIDE of the corner.
      //
      // NOTE: trackdef's docstring says "positive curvature = turning left",
      // but the maths says otherwise — it builds `cross = a.x*b.z - a.z*b.x`,
      // which is MINUS the y component of a x b, so a positive value is a
      // clockwise (right-hand) turn. Verified on screen: with the naive reading
      // every kerb landed on the outside of its corner. Inside == sign(c).
      const rs = ranges(RINGS, i => {
        const c = curvOf(i);
        return Math.abs(c) > KERB_T && Math.sign(c) === sgn;
      }, 4);
      for (const [i0, i1] of rs) {
        // extend a little into the entry/exit like a real kerb does
        const a = i0 - 3, b = i1 + 3;
        const sub = [];
        for (let i = a; i <= b; i++) sub.push(i / RINGS);
        sweep(mb, spline, sub, (t, i, ramp) => {
          const w = spline.widthAt(t);
          const h = 0.16 * ramp;
          return [
            { l: sgn * (w - 0.05), h: 0.012, u: 0 },
            { l: sgn * (w + 0.16), h: h * 0.62, u: 0.12 },
            { l: sgn * (w + 1.35), h, u: 0.86 },
            { l: sgn * (w + 1.55), h: 0.0, u: 1.0 },
          ];
        }, { vScale: M.kerbLen, taper: 5 });
      }
    }
    if (mb.count) {
      const g = mb.geometry(); geos.push(g);
      const kerbs = new THREE.Mesh(g, kerbMat);
      kerbs.castShadow = !!q.shadows; kerbs.receiveShadow = !!q.shadows;
      kerbs.name = 'kerbs';
      group.add(kerbs);
    }
  }

  // =========================================================================
  // 4. RUN-OFF APRON — sand out to the wall line (physics wall = w + 5.5)
  // =========================================================================
  const RUNOFF = 5.5;
  const sandMaps = tileable(sandTexture({ size: S, tint: P.sandTint, ripple: def.theme === 'oasis' ? 1 : 0.35 }));
  const vergeMat = keep(stdMat(sandMaps, { vertexColors: true }));
  {
    const mb = new MB(true);
    for (const side of [-1, 1]) {
      sweep(mb, spline, ts, (t) => {
        const w = spline.widthAt(t);
        const n1 = fbm(noise, t * 90, side * 3.1, 3);
        const sec = [];
        const stops = [0.0, 0.10, 0.34, 0.68, 1.0];
        for (const f of stops) {
          const l = side * (w + f * RUNOFF);
          // dips away from the road so water/sand reads as run-off, not a shelf
          const h = -0.03 - Math.pow(f, 1.6) * (0.42 + n1 * 0.3);
          // darker, damper sand further out; a bleached strip right at the edge
          const k = lerp(1.12, 0.82, f) * (0.92 + n1 * 0.18);
          sec.push({ l, h, u: l / M.sand, col: [k, k * 0.98, k * 0.94] });
        }
        return sec;
      }, { vScale: M.sand, closed: true });
    }
    const g = mb.geometry(); geos.push(g);
    const verge = new THREE.Mesh(g, vergeMat);
    verge.receiveShadow = !!q.shadows;
    verge.name = 'runoff';
    group.add(verge);
  }

  // =========================================================================
  // 5. TERRAIN — carved so it can never poke through the road
  // =========================================================================
  const relief = (x, z) => {
    const a = fbm(noise, x * 0.0042, z * 0.0042, 4) - 0.5;
    const b = fbm(noise, x * 0.017 + 11, z * 0.017 - 7, 3) - 0.5;
    const c = fbm(noise, x * 0.055 - 3, z * 0.055 + 5, 2) - 0.5;
    return a * 30 + b * 6.5 + c * 1.4;
  };
  const FLAT = RUNOFF + 1.2, BLEND = 46;
  const heightAt = (x, z) => {
    const s = spline.closestT(new THREE.Vector3(x, 0, z));
    const d = Math.abs(s.lateral);
    const w = spline.widthAt(s.t);
    const k = sstep(w + FLAT, w + BLEND, d);
    const base = s.pos.y - 0.55;
    return base + k * (relief(x, z) + 3.2 * k);
  };
  {
    const b = spline.bounds;
    const cx = (b.minX + b.maxX) / 2, cz = (b.minZ + b.maxZ) / 2;
    const pad = 340;
    const sx = (b.maxX - b.minX) + pad * 2, sz = (b.maxZ - b.minZ) + pad * 2;
    const N = q.propDensity >= 0.9 ? 168 : q.propDensity >= 0.6 ? 120 : 76;
    const geo = new THREE.PlaneGeometry(sx, sz, N, N);
    geo.rotateX(-Math.PI / 2);
    const pos = geo.attributes.position;
    const col = new Float32Array(pos.count * 3);
    const v = new THREE.Vector3();
    for (let i = 0; i < pos.count; i++) {
      const x = pos.getX(i) + cx, z = pos.getZ(i) + cz;
      v.set(x, 0, z);
      const s = spline.closestT(v);
      const d = Math.abs(s.lateral);
      const w = spline.widthAt(s.t);
      const k = sstep(w + FLAT, w + BLEND, d);
      const y = s.pos.y - 0.55 + k * (relief(x, z) + 3.2 * k);
      pos.setXYZ(i, pos.getX(i), y, pos.getZ(i));
      // tonal variation: ochre flats, redder on the rises, pale in the hollows
      const n = fbm(noise, x * 0.009 + 3, z * 0.009 - 2, 3);
      const rise = clamp01((y - s.pos.y) / 22);
      const r = lerp(0.86, 1.14, n) * lerp(1.0, 1.10, rise);
      col[i * 3] = r * 1.02; col[i * 3 + 1] = r * 0.94; col[i * 3 + 2] = r * 0.84;
    }
    geo.setAttribute('color', new THREE.Float32BufferAttribute(col, 3));
    geo.computeVertexNormals();
    geo.translate(cx, 0, cz);
    geos.push(geo);
    // Terrain is mostly seen at 60-400 m, so it gets its own low-contrast sand
    // at a much coarser tile (36 m): a road-scale tile out here turns into a
    // shimmering moire carpet, which is the other classic procedural tell.
    const groundMaps = tileable(sandTexture({ size: S, tint: P.dustTint, ripple: 0.25, seed: 91 }));
    const TILE = 36;
    const gmat = keep(new THREE.MeshStandardMaterial({
      map: groundMaps.map, roughness: 1, metalness: 0, vertexColors: true,
    }));
    gmat.map.repeat.set(sx / TILE, sz / TILE);
    gmat.map.offset.set(cx / TILE, cz / TILE);
    const ground = new THREE.Mesh(geo, gmat);
    ground.receiveShadow = !!q.shadows;
    ground.name = 'terrain';
    ground.renderOrder = -5;
    group.add(ground);
  }

  // =========================================================================
  // 6. BARRIERS — coursed sandstone blocks, with variation
  // =========================================================================
  const wallMaps = tileable(stoneWallTexture({
    size: S, tint: P.wall, mortar: P.wallMortar, rows: 3, cols: 4,
  }));
  const wallMat = keep(stdMat(wallMaps, { vertexColors: true, roughness: 0.95 }));
  {
    const mb = new MB(true);
    const TH = 0.62;
    for (const side of [-1, 1]) {
      sweep(mb, spline, ts, (t, i) => {
        const w = spline.widthAt(t);
        const n1 = fbm(noise, t * 130 + (side > 0 ? 40 : 0), side * 7, 3);
        const n2 = fbm(noise, t * 480, side * 2.5, 2);
        const h = 1.02 + n1 * 0.42;                    // 1.0 - 1.45 m
        const b = w + RUNOFF;                          // matches the physics wall
        const k = 0.86 + n1 * 0.26 + n2 * 0.10;        // per-ring block tone
        const col = [k, k * 0.985, k * 0.95];
        // inner face -> capstone -> outer face, uv.y = height/1.05 (3 courses)
        return [
          { l: side * b, h: -0.5, u: -0.5 / M.wallHigh, col },
          { l: side * b, h, u: h / M.wallHigh, col },
          { l: side * (b + TH * 0.5), h: h + 0.075, u: (h + 0.6) / M.wallHigh, col: [k * 1.1, k * 1.08, k * 1.04] },
          { l: side * (b + TH), h, u: (h + 1.2) / M.wallHigh, col },
          { l: side * (b + TH), h: -0.6, u: (h + 1.9) / M.wallHigh, col },
        ];
      }, { vScale: M.wallLen, swapUV: true, closed: true });
    }
    const g = mb.geometry(); geos.push(g);
    const wall = new THREE.Mesh(g, wallMat);
    wall.castShadow = !!q.shadows; wall.receiveShadow = !!q.shadows;
    wall.name = 'barrier';
    group.add(wall);
  }

  // =========================================================================
  // 7. CATCH FENCING on the outside of fast corners
  // =========================================================================
  const metalMaps = tileable(metalTexture({ size: Math.min(S, 512), tint: 0x9aa2ab }));
  const fenceMat = keep(stdMat(metalMaps, { color: 0x7d7f84, metalness: 0.45, roughness: 0.62 }));
  {
    const mb = new MB(false);
    const postGeo = new THREE.CylinderGeometry(0.07, 0.09, 2.45, 6);
    const posts = [];
    for (const sgn of [-1, 1]) {
      const rs = ranges(RINGS, i => {
        const c = curvOf(i);
        return Math.abs(c) > 0.135 && Math.sign(c) === -sgn;  // outside of the turn
      }, 6);
      for (const [i0, i1] of rs) {
        const sub = [];
        for (let i = i0 - 4; i <= i1 + 4; i++) sub.push(i / RINGS);
        // slim horizontal rails — catch fencing, not a motorway guardrail
        for (const [hy, th] of [[1.30, 0.035], [1.95, 0.035], [2.55, 0.055]]) {
          sweep(mb, spline, sub, (t, i, ramp) => {
            const w = spline.widthAt(t) + RUNOFF + 0.40;
            const y = hy * ramp + 0.9 * (1 - ramp);
            return [
              { l: sgn * (w - 0.05), h: y - th, u: 0 },
              { l: sgn * (w - 0.05), h: y + th, u: 0.5 },
              { l: sgn * (w + 0.05), h: y + th, u: 1 },
              { l: sgn * (w + 0.05), h: y - th, u: 0.5 },
            ];
          }, { vScale: 2.5, taper: 4 });
        }
        const step = Math.max(1, Math.round(3.2 / (L / RINGS)));
        for (let i = i0; i <= i1; i += step) {
          const t = ((i / RINGS) % 1 + 1) % 1;
          const fr = spline.frameAt(t);
          const w = spline.widthAt(t) + RUNOFF + 0.40;
          posts.push([fr.pos.x + fr.right.x * sgn * w, fr.pos.y + 1.35, fr.pos.z + fr.right.z * sgn * w]);
        }
      }
    }
    if (mb.count) {
      const g = mb.geometry(); geos.push(g);
      const rails = new THREE.Mesh(g, fenceMat);
      rails.castShadow = !!q.shadows;
      rails.name = 'fence-rails';
      group.add(rails);
    }
    if (posts.length) {
      geos.push(postGeo);
      const im = new THREE.InstancedMesh(postGeo, fenceMat, posts.length);
      const m4 = new THREE.Matrix4();
      posts.forEach((p, i) => { m4.makeTranslation(p[0], p[1], p[2]); im.setMatrixAt(i, m4); });
      im.instanceMatrix.needsUpdate = true;
      im.castShadow = !!q.shadows;
      im.name = 'fence-posts';
      group.add(im);
    } else postGeo.dispose();
  }

  // =========================================================================
  // 8. START / FINISH — chequer, gantry, flags
  // =========================================================================
  const startT = def.startT ?? 0;
  {
    const chequer = chequerTexture(128);
    chequer.wrapS = chequer.wrapT = THREE.RepeatWrapping;
    const chqMat = keep(new THREE.MeshStandardMaterial({
      map: chequer, roughness: 0.8, metalness: 0,
      polygonOffset: true, polygonOffsetFactor: -6, polygonOffsetUnits: -8,
    }));
    const mb = new MB(false);
    const wStart = spline.widthAt(startT);
    const dT = 1.9 / L;
    const rows = 8;
    for (let r = 0; r <= rows; r++) {
      const tt = startT - dT / 2 + (r / rows) * dT;
      const fr = spline.frameAt(((tt % 1) + 1) % 1);
      const base = mb.count;
      const cols = 2;
      for (let c = 0; c <= cols; c++) {
        const l = (c / cols * 2 - 1) * wStart;
        mb.vert(fr.pos.x + fr.right.x * l, fr.pos.y + 0.02, fr.pos.z + fr.right.z * l,
          l / (wStart * 2 / 6), r / rows * 1);      // 6 chequer tiles across
      }
      if (r > 0) {
        const prev = base - (cols + 1);
        for (let c = 0; c < cols; c++) mb.quad(prev + c, prev + c + 1, base + c + 1, base + c);
      }
    }
    const g = mb.geometry(); geos.push(g);
    const line = new THREE.Mesh(g, chqMat);
    line.name = 'startline';
    group.add(line);

    // --- gantry ------------------------------------------------------------
    const fr = spline.frameAt(startT);
    const woodMaps = tileable(woodTexture({ size: Math.min(S, 512), tint: 0xb9884f }));
    const woodMat = keep(stdMat(woodMaps, { roughness: 0.92 }));
    // the artwork lives in the top quarter of the (square) canvas, so the board
    // samples only that band — full texel density on a 4:1 banner
    const gTex = gantryTexture(def.nameHe, 1024);
    gTex.repeat.set(1, 0.25); gTex.offset.set(0, 0.75);
    // FrontSide, one board per direction: a DoubleSide banner shows mirrored
    // Hebrew to anyone standing behind it.
    const gMat = keep(new THREE.MeshStandardMaterial({
      map: gTex, roughness: 0.75, side: THREE.FrontSide, emissive: 0x2a1a0c, emissiveIntensity: 0.35,
    }));

    const gan = new THREE.Group();
    gan.name = 'gantry';
    const span = wStart + RUNOFF + 1.4;   // legs stand outside the barrier
    const HGT = 6.2;
    // legs + cross-bracing, in one merged wooden geometry
    const wmb = new MB(false);
    for (const s of [-1, 1]) {
      wmb.box(s * span, HGT / 2, 0, 0.85, HGT, 0.85, 0.35);
      wmb.box(s * span, HGT + 0.35, 0, 1.3, 0.7, 1.3, 0.35);
      wmb.box(s * (span - 0.9), 1.1, 0, 2.1, 0.5, 0.55, 0.35);
      // diagonal-ish braces (as short boxes, rotated in the XZ plane is enough)
      wmb.box(s * span, HGT * 0.55, 0, 0.5, 3.4, 0.5, 0.35);
    }
    // the beam itself
    const beamW = span * 2 + 1.6;
    const boardH = Math.min(3.0, beamW / 9);
    wmb.box(0, HGT + 0.30, 0, beamW, 0.42, 1.35, 0.3);
    wmb.box(0, HGT + 0.60 + boardH, 0, beamW, 0.34, 1.35, 0.3);
    const wg = wmb.geometry(); geos.push(wg);
    const legs = new THREE.Mesh(wg, woodMat);
    legs.castShadow = !!q.shadows; legs.receiveShadow = !!q.shadows;
    gan.add(legs);

    const boardGeo = new THREE.PlaneGeometry(beamW - 0.3, boardH);
    geos.push(boardGeo);
    for (const side of [0, Math.PI]) {
      const board = new THREE.Mesh(boardGeo, gMat);
      board.position.set(0, HGT + 0.45 + boardH / 2, side ? -0.14 : 0.14);
      board.rotation.y = side;
      board.castShadow = false;
      gan.add(board);
    }
    // pennants along the top of the beam, for silhouette
    {
      const stripes = stripeTexture({ size: 128, colors: [0xd94f3d, 0xf5ead6], count: 3 });
      const fmb = new MB(false);
      const nF = 6;
      for (let i = 0; i < nF; i++) {
        const x = (i / (nF - 1) - 0.5) * (beamW - 1.6);
        const y0 = HGT + 0.85 + boardH;
        const n0 = fmb.count;
        fmb.vert(x - 0.80, y0, 0, 0, 0); fmb.vert(x + 0.80, y0, 0, 1, 0);
        fmb.vert(x + 0.80, y0 + 1.75, 0, 1, 1); fmb.vert(x - 0.80, y0 + 1.75, 0, 0, 1);
        fmb.quad(n0, n0 + 1, n0 + 2, n0 + 3);
        fmb.box(x, y0 + 0.88, -0.06, 0.07, 1.8, 0.07, 1);
      }
      const fg = fmb.geometry(); geos.push(fg);
      const fmat = keep(new THREE.MeshStandardMaterial({ map: stripes, roughness: 0.9, side: THREE.DoubleSide }));
      const flags = new THREE.Mesh(fg, fmat);
      flags.castShadow = !!q.shadows;
      gan.add(flags);
    }
    // orient the gantry across the track: local +Z runs along the tangent, so
    // the legs (local +/-X) straddle the road.
    gan.position.copy(fr.pos);
    gan.rotation.y = Math.atan2(fr.tan.x, fr.tan.z);
    group.add(gan);
  }

  // =========================================================================
  // 9. CHECKPOINTS + TOKEN SPOTS
  // =========================================================================
  const CP = 16;
  const checkpoints = [];
  for (let i = 0; i < CP; i++) checkpoints.push(((startT + i / CP) % 1 + 1) % 1);

  // Smoothed racing line: hug the inside of corners, drift wide on entry/exit.
  const lineLat = new Float32Array(RINGS);
  for (let i = 0; i < RINGS; i++) {
    let c = 0;
    for (let k = -8; k <= 8; k++) c += spline.curvatureAt(((i + k) / RINGS % 1 + 1) % 1);
    c /= 17;
    const w = spline.widthAt(i / RINGS);
    lineLat[i] = Math.sign(c) * Math.min(1, Math.abs(c) / 0.22) * w * 0.52;
  }
  const tokenSpots = [];
  {
    const clusters = 8;
    for (let g2 = 0; g2 < clusters; g2++) {
      // sit the clusters just before the apex of the biggest corners and on the
      // fast straights, so they both reward the good line and bait a dive inside
      const t = ((startT + (g2 + 0.5) / clusters) % 1 + 1) % 1;
      const i = Math.floor(t * RINGS) % RINGS;
      const w = spline.widthAt(t);
      const corner = Math.min(1, Math.abs(spline.curvatureAt(t)) / 0.2);
      const centre = lerp(0, lineLat[i], corner);
      const spreads = corner > 0.4 ? [-0.34, 0, 0.34] : [-0.55, -0.18, 0.18, 0.55];
      for (const s of spreads) {
        const lat = clamp(centre + s * w, -w * 0.82, w * 0.82);
        const p = spline.offsetPoint(t, lat);
        p.y += 1.05;
        tokenSpots.push(p);
      }
    }
  }

  // =========================================================================
  // 10. SCENERY DRESSING
  // =========================================================================
  group.userData.heightAt = heightAt;
  group.userData.runoff = RUNOFF;
  group.userData.theme = def.theme;
  group.userData.palette = P;

  let dress = null;
  if (opts.dress !== false) {
    dress = dressTrack(group, spline, def, engine, makeRng(7700 + def.points.length));
  }

  void rockTexture; void metalMaps;

  const api = {
    group, spline, def, checkpoints, tokenSpots, heightAt, dress,
    update(time) { dress?.update?.(time); },
    dispose() {
      dress?.dispose?.();
      for (const g of geos) g.dispose?.();
      for (const m of mats) m.dispose?.();
      for (const d of disposables) d.dispose?.();
      group.traverse(o => { if (o.isInstancedMesh) o.dispose?.(); });
      group.clear();
    },
  };
  return api;
}

function clamp(v, a, b) { return v < a ? a : v > b ? b : v; }

// ===========================================================================
// PREVIEWS
// ===========================================================================

function baseScene(engine, trackId = 'oasis') {
  const scene = new THREE.Scene();
  const { def } = getTrack(trackId);
  const rig = applyTheme(scene, def.theme, engine);
  const track = buildTrack(trackId, engine);
  scene.add(track.group);
  const camera = new THREE.PerspectiveCamera(58, 16 / 9, 0.15, 3000);
  return { scene, camera, rig, track, def };
}

function wrap(engine, ctx, place) {
  const { scene, camera, rig, track } = ctx;
  place(camera, track, rig);
  let t = 0;
  return {
    scene, camera, rig, track,
    update(dt) {
      t += dt;
      track.update(t);
      rig.update(dt, camera);
    },
    resize(w, h) { camera.aspect = w / h; camera.updateProjectionMatrix(); },
    dispose() {
      track.dispose();
      rig.dispose();
      disposeTextureCache();
    },
  };
}

/**
 * Driver's-eye view from just behind the start line, looking down the track —
 * the A/B frame against the reference art.
 */
export function preview(engine) {
  const ctx = baseScene(engine, 'oasis');
  return wrap(engine, ctx, (camera, track, rig) => {
    const sp = track.spline, def = track.def;
    // Framed to match reference/image4.png: driver eye height, road filling the
    // lower half, the gantry sitting just inside the top edge rather than
    // hanging over the lens.
    const t0 = ((def.startT - 42 / sp.length) % 1 + 1) % 1;
    const p = sp.offsetPoint(t0, 0.8);
    camera.position.set(p.x, p.y + 2.05, p.z);
    const look = sp.offsetPoint(((def.startT + 90 / sp.length) % 1 + 1) % 1, -0.6);
    camera.lookAt(look.x, look.y + 5.2, look.z);
    rig.setShadowFocus(p);
  });
}

/** Sitting on the grid, right under the gantry — the pre-race hero shot. */
export function previewGrid(engine) {
  const ctx = baseScene(engine, 'oasis');
  return wrap(engine, ctx, (camera, track, rig) => {
    const sp = track.spline, def = track.def;
    const t0 = ((def.startT - 13 / sp.length) % 1 + 1) % 1;
    const p = sp.offsetPoint(t0, 0.8);
    camera.position.set(p.x, p.y + 1.55, p.z);
    const look = sp.offsetPoint(((def.startT + 55 / sp.length) % 1 + 1) % 1, -0.6);
    camera.lookAt(look.x, look.y + 3.6, look.z);
    rig.setShadowFocus(p);
  });
}

/** High wide shot showing the whole circuit layout. */
export function previewAerial(engine) {
  const ctx = baseScene(engine, 'oasis');
  return wrap(engine, ctx, (camera, track, rig) => {
    const b = track.spline.bounds;
    const cx = (b.minX + b.maxX) / 2, cz = (b.minZ + b.maxZ) / 2;
    const r = Math.max(b.maxX - b.minX, b.maxZ - b.minZ);
    camera.fov = 46; camera.updateProjectionMatrix();
    camera.position.set(cx + r * 0.30, r * 0.72, cz + r * 0.78);
    camera.lookAt(cx, 0, cz - r * 0.02);
    // a wide layout shot needs to see the layout: thin the haze right down
    rig.fog.density *= 0.16;
    rig.setShadowFocus(new THREE.Vector3(cx, 0, cz));
  });
}

/** Three-quarter view of a dressed corner: kerbs, barrier, crowd. */
export function previewCorner(engine) {
  const ctx = baseScene(engine, 'oasis');
  return wrap(engine, ctx, (camera, track, rig) => {
    const sp = track.spline;
    // find the tightest corner
    let best = 0, bestC = 0;
    for (let i = 0; i < 400; i++) {
      const t = i / 400;
      // stay away from the start/finish complex — that is preview()'s job
      const d = Math.min(Math.abs(t - track.def.startT), 1 - Math.abs(t - track.def.startT));
      if (d < 0.18) continue;
      const c = Math.abs(sp.curvatureAt(t));
      if (c > bestC) { bestC = c; best = t; }
    }
    const apexT = ((best - 30 / sp.length) % 1 + 1) % 1;
    const sgn = Math.sign(sp.curvatureAt(best)) || 1;   // outside of the corner
    const w = sp.widthAt(apexT);
    // Framed like reference/image5.png: sitting on the racing line at corner
    // entry, kerb and barrier sweeping past on the inside.
    // Corner entry on the outside, aimed straight at the apex kerb 20 m away —
    // the kerb, its barrier and the crowd behind it fill the middle of frame.
    // Framed like reference/image5.png: running the inside line into the apex,
    // so the kerb, its barrier and the crowd behind sweep past down one side of
    // frame instead of sitting as a dot in the middle distance.
    // Framed like reference/image5.png: corner entry from the outside line,
    // aimed squarely at the apex kerb 30 m ahead, so kerb, barrier and crowd
    // occupy the middle of frame rather than the edge of it.
    const eye = sp.offsetPoint(apexT, -sgn * (w * 0.85));
    const look = sp.offsetPoint(best, sgn * (w + 0.8));
    camera.fov = 54; camera.updateProjectionMatrix();
    camera.position.set(eye.x, eye.y + 1.60, eye.z);
    camera.lookAt(look.x, look.y + 0.85, look.z);
    rig.setShadowFocus(look);
  });
}
