import puppeteer from 'puppeteer-core';
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const b=await puppeteer.launch({executablePath:CHROME,headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--force-device-scale-factor=1','--hide-scrollbars','--mute-audio']});
const p=await b.newPage(); p.on('pageerror',e=>console.log('PAGEERROR',e.message));
await p.setViewport({width:1440,height:900});
await p.goto('file:///Users/yoyopc/repos/kart-project/.tmp/critic/probe.html',{waitUntil:'load'});
await p.waitForFunction('window.__DEBUG&&window.__DEBUG.ready===true',{timeout:60000});
const w=ms=>new Promise(r=>setTimeout(r,ms)); await w(600);
const sig=()=>p.evaluate(()=>{const k=window.__KART;let m=0;k.group.traverse(o=>{if(o.isMesh)m++;});return m;});
const cards=()=>p.evaluate(()=>[...document.querySelectorAll('.grg-opt')].map(c=>c.querySelector('.grg-opt-he')?.textContent.trim()));
const click=async i=>{await p.evaluate(n=>document.querySelectorAll('.grg-opt')[n].click(),i);await w(450);};
const back=async()=>{await p.evaluate(()=>document.querySelector('.grg-back').click());await w(350);};
const shot=async n=>p.screenshot({path:'/Users/yoyopc/repos/kart-project/shots/critic-garage/k4-'+n+'.png',clip:{x:26,y:205,width:372,height:235}});
const log=async n=>console.log(n.padEnd(22),'meshes='+await sig(),'tiers='+JSON.stringify(await p.evaluate(()=>window.__TIERS)));
// SINGLE scene, wizard driven by clicks only
await click(0); await log('picked engine'); await shot('01-engine');
await click(0); await log('goal vague(lvl0)'); await shot('02-goal-vague');
await back(); await click(3); await log('goal sharp(lvl3)'); await shot('03-goal-sharp');
await back(); await click(0); await log('goal vague again'); await shot('04-goal-vague2');
await b.close();
